/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfirmEmailRouteImport } from './routes/confirm-email'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TournamentsIndexRouteImport } from './routes/tournaments/index'
import { Route as PlayersIndexRouteImport } from './routes/players/index'
import { Route as MatchesIndexRouteImport } from './routes/matches/index'
import { Route as LoginIndexRouteImport } from './routes/login.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TournamentsTournamentIdRouteImport } from './routes/tournaments.$tournamentId'
import { Route as PlayersUserIdRouteImport } from './routes/players/$userId'
import { Route as MatchesNewRouteImport } from './routes/matches/new'
import { Route as LoginWelcomeRouteImport } from './routes/login.welcome'
import { Route as LoginVerifyingRouteImport } from './routes/login.verifying'
import { Route as LoginSentRouteImport } from './routes/login.sent'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminPermissionsRouteImport } from './routes/admin.permissions'
import { Route as MatchesMatchIdIndexRouteImport } from './routes/matches.$matchId.index'
import { Route as PPlayersUsernameRouteImport } from './routes/p.players.$username'
import { Route as PMatchesMatchIdRouteImport } from './routes/p.matches.$matchId'
import { Route as MatchesMatchIdGamesGameNumberScoresNewRouteImport } from './routes/matches.$matchId.games.$gameNumber.scores.new'
import { Route as MatchesMatchIdGamesGameNumberScoresEditRouteImport } from './routes/matches.$matchId.games.$gameNumber.scores.edit'

const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmEmailRoute = ConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIndexRoute = TournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIndexRoute = PlayersIndexRouteImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIndexRoute = MatchesIndexRouteImport.update({
  id: '/matches/',
  path: '/matches/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TournamentsTournamentIdRoute = TournamentsTournamentIdRouteImport.update({
  id: '/tournaments/$tournamentId',
  path: '/tournaments/$tournamentId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersUserIdRoute = PlayersUserIdRouteImport.update({
  id: '/players/$userId',
  path: '/players/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesNewRoute = MatchesNewRouteImport.update({
  id: '/matches/new',
  path: '/matches/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginWelcomeRoute = LoginWelcomeRouteImport.update({
  id: '/login/welcome',
  path: '/login/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginVerifyingRoute = LoginVerifyingRouteImport.update({
  id: '/login/verifying',
  path: '/login/verifying',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginSentRoute = LoginSentRouteImport.update({
  id: '/login/sent',
  path: '/login/sent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPermissionsRoute = AdminPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AdminRoute,
} as any)
const MatchesMatchIdIndexRoute = MatchesMatchIdIndexRouteImport.update({
  id: '/matches/$matchId/',
  path: '/matches/$matchId/',
  getParentRoute: () => rootRouteImport,
} as any)
const PPlayersUsernameRoute = PPlayersUsernameRouteImport.update({
  id: '/p/players/$username',
  path: '/p/players/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PMatchesMatchIdRoute = PMatchesMatchIdRouteImport.update({
  id: '/p/matches/$matchId',
  path: '/p/matches/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesMatchIdGamesGameNumberScoresNewRoute =
  MatchesMatchIdGamesGameNumberScoresNewRouteImport.update({
    id: '/matches/$matchId/games/$gameNumber/scores/new',
    path: '/matches/$matchId/games/$gameNumber/scores/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const MatchesMatchIdGamesGameNumberScoresEditRoute =
  MatchesMatchIdGamesGameNumberScoresEditRouteImport.update({
    id: '/matches/$matchId/games/$gameNumber/scores/edit',
    path: '/matches/$matchId/games/$gameNumber/scores/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/confirm-email': typeof ConfirmEmailRoute
  '/dashboard': typeof DashboardRoute
  '/design-system': typeof DesignSystemRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/login/sent': typeof LoginSentRoute
  '/login/verifying': typeof LoginVerifyingRoute
  '/login/welcome': typeof LoginWelcomeRoute
  '/matches/new': typeof MatchesNewRoute
  '/players/$userId': typeof PlayersUserIdRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdRoute
  '/admin/': typeof AdminIndexRoute
  '/login/': typeof LoginIndexRoute
  '/matches/': typeof MatchesIndexRoute
  '/players/': typeof PlayersIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/p/matches/$matchId': typeof PMatchesMatchIdRoute
  '/p/players/$username': typeof PPlayersUsernameRoute
  '/matches/$matchId/': typeof MatchesMatchIdIndexRoute
  '/matches/$matchId/games/$gameNumber/scores/edit': typeof MatchesMatchIdGamesGameNumberScoresEditRoute
  '/matches/$matchId/games/$gameNumber/scores/new': typeof MatchesMatchIdGamesGameNumberScoresNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/dashboard': typeof DashboardRoute
  '/design-system': typeof DesignSystemRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/login/sent': typeof LoginSentRoute
  '/login/verifying': typeof LoginVerifyingRoute
  '/login/welcome': typeof LoginWelcomeRoute
  '/matches/new': typeof MatchesNewRoute
  '/players/$userId': typeof PlayersUserIdRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdRoute
  '/admin': typeof AdminIndexRoute
  '/login': typeof LoginIndexRoute
  '/matches': typeof MatchesIndexRoute
  '/players': typeof PlayersIndexRoute
  '/tournaments': typeof TournamentsIndexRoute
  '/p/matches/$matchId': typeof PMatchesMatchIdRoute
  '/p/players/$username': typeof PPlayersUsernameRoute
  '/matches/$matchId': typeof MatchesMatchIdIndexRoute
  '/matches/$matchId/games/$gameNumber/scores/edit': typeof MatchesMatchIdGamesGameNumberScoresEditRoute
  '/matches/$matchId/games/$gameNumber/scores/new': typeof MatchesMatchIdGamesGameNumberScoresNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/confirm-email': typeof ConfirmEmailRoute
  '/dashboard': typeof DashboardRoute
  '/design-system': typeof DesignSystemRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/login/sent': typeof LoginSentRoute
  '/login/verifying': typeof LoginVerifyingRoute
  '/login/welcome': typeof LoginWelcomeRoute
  '/matches/new': typeof MatchesNewRoute
  '/players/$userId': typeof PlayersUserIdRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdRoute
  '/admin/': typeof AdminIndexRoute
  '/login/': typeof LoginIndexRoute
  '/matches/': typeof MatchesIndexRoute
  '/players/': typeof PlayersIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/p/matches/$matchId': typeof PMatchesMatchIdRoute
  '/p/players/$username': typeof PPlayersUsernameRoute
  '/matches/$matchId/': typeof MatchesMatchIdIndexRoute
  '/matches/$matchId/games/$gameNumber/scores/edit': typeof MatchesMatchIdGamesGameNumberScoresEditRoute
  '/matches/$matchId/games/$gameNumber/scores/new': typeof MatchesMatchIdGamesGameNumberScoresNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/confirm-email'
    | '/dashboard'
    | '/design-system'
    | '/settings'
    | '/simulator'
    | '/admin/permissions'
    | '/admin/roles'
    | '/admin/users'
    | '/login/sent'
    | '/login/verifying'
    | '/login/welcome'
    | '/matches/new'
    | '/players/$userId'
    | '/tournaments/$tournamentId'
    | '/admin/'
    | '/login/'
    | '/matches/'
    | '/players/'
    | '/tournaments/'
    | '/p/matches/$matchId'
    | '/p/players/$username'
    | '/matches/$matchId/'
    | '/matches/$matchId/games/$gameNumber/scores/edit'
    | '/matches/$matchId/games/$gameNumber/scores/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confirm-email'
    | '/dashboard'
    | '/design-system'
    | '/settings'
    | '/simulator'
    | '/admin/permissions'
    | '/admin/roles'
    | '/admin/users'
    | '/login/sent'
    | '/login/verifying'
    | '/login/welcome'
    | '/matches/new'
    | '/players/$userId'
    | '/tournaments/$tournamentId'
    | '/admin'
    | '/login'
    | '/matches'
    | '/players'
    | '/tournaments'
    | '/p/matches/$matchId'
    | '/p/players/$username'
    | '/matches/$matchId'
    | '/matches/$matchId/games/$gameNumber/scores/edit'
    | '/matches/$matchId/games/$gameNumber/scores/new'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/confirm-email'
    | '/dashboard'
    | '/design-system'
    | '/settings'
    | '/simulator'
    | '/admin/permissions'
    | '/admin/roles'
    | '/admin/users'
    | '/login/sent'
    | '/login/verifying'
    | '/login/welcome'
    | '/matches/new'
    | '/players/$userId'
    | '/tournaments/$tournamentId'
    | '/admin/'
    | '/login/'
    | '/matches/'
    | '/players/'
    | '/tournaments/'
    | '/p/matches/$matchId'
    | '/p/players/$username'
    | '/matches/$matchId/'
    | '/matches/$matchId/games/$gameNumber/scores/edit'
    | '/matches/$matchId/games/$gameNumber/scores/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ConfirmEmailRoute: typeof ConfirmEmailRoute
  DashboardRoute: typeof DashboardRoute
  DesignSystemRoute: typeof DesignSystemRoute
  SettingsRoute: typeof SettingsRoute
  SimulatorRoute: typeof SimulatorRoute
  LoginSentRoute: typeof LoginSentRoute
  LoginVerifyingRoute: typeof LoginVerifyingRoute
  LoginWelcomeRoute: typeof LoginWelcomeRoute
  MatchesNewRoute: typeof MatchesNewRoute
  PlayersUserIdRoute: typeof PlayersUserIdRoute
  TournamentsTournamentIdRoute: typeof TournamentsTournamentIdRoute
  LoginIndexRoute: typeof LoginIndexRoute
  MatchesIndexRoute: typeof MatchesIndexRoute
  PlayersIndexRoute: typeof PlayersIndexRoute
  TournamentsIndexRoute: typeof TournamentsIndexRoute
  PMatchesMatchIdRoute: typeof PMatchesMatchIdRoute
  PPlayersUsernameRoute: typeof PPlayersUsernameRoute
  MatchesMatchIdIndexRoute: typeof MatchesMatchIdIndexRoute
  MatchesMatchIdGamesGameNumberScoresEditRoute: typeof MatchesMatchIdGamesGameNumberScoresEditRoute
  MatchesMatchIdGamesGameNumberScoresNewRoute: typeof MatchesMatchIdGamesGameNumberScoresNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm-email': {
      id: '/confirm-email'
      path: '/confirm-email'
      fullPath: '/confirm-email'
      preLoaderRoute: typeof ConfirmEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/': {
      id: '/tournaments/'
      path: '/tournaments'
      fullPath: '/tournaments/'
      preLoaderRoute: typeof TournamentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/': {
      id: '/players/'
      path: '/players'
      fullPath: '/players/'
      preLoaderRoute: typeof PlayersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/': {
      id: '/matches/'
      path: '/matches'
      fullPath: '/matches/'
      preLoaderRoute: typeof MatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tournaments/$tournamentId': {
      id: '/tournaments/$tournamentId'
      path: '/tournaments/$tournamentId'
      fullPath: '/tournaments/$tournamentId'
      preLoaderRoute: typeof TournamentsTournamentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$userId': {
      id: '/players/$userId'
      path: '/players/$userId'
      fullPath: '/players/$userId'
      preLoaderRoute: typeof PlayersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/new': {
      id: '/matches/new'
      path: '/matches/new'
      fullPath: '/matches/new'
      preLoaderRoute: typeof MatchesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/welcome': {
      id: '/login/welcome'
      path: '/login/welcome'
      fullPath: '/login/welcome'
      preLoaderRoute: typeof LoginWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/verifying': {
      id: '/login/verifying'
      path: '/login/verifying'
      fullPath: '/login/verifying'
      preLoaderRoute: typeof LoginVerifyingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/sent': {
      id: '/login/sent'
      path: '/login/sent'
      fullPath: '/login/sent'
      preLoaderRoute: typeof LoginSentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/permissions': {
      id: '/admin/permissions'
      path: '/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AdminPermissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/matches/$matchId/': {
      id: '/matches/$matchId/'
      path: '/matches/$matchId'
      fullPath: '/matches/$matchId/'
      preLoaderRoute: typeof MatchesMatchIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/players/$username': {
      id: '/p/players/$username'
      path: '/p/players/$username'
      fullPath: '/p/players/$username'
      preLoaderRoute: typeof PPlayersUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/matches/$matchId': {
      id: '/p/matches/$matchId'
      path: '/p/matches/$matchId'
      fullPath: '/p/matches/$matchId'
      preLoaderRoute: typeof PMatchesMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$matchId/games/$gameNumber/scores/new': {
      id: '/matches/$matchId/games/$gameNumber/scores/new'
      path: '/matches/$matchId/games/$gameNumber/scores/new'
      fullPath: '/matches/$matchId/games/$gameNumber/scores/new'
      preLoaderRoute: typeof MatchesMatchIdGamesGameNumberScoresNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$matchId/games/$gameNumber/scores/edit': {
      id: '/matches/$matchId/games/$gameNumber/scores/edit'
      path: '/matches/$matchId/games/$gameNumber/scores/edit'
      fullPath: '/matches/$matchId/games/$gameNumber/scores/edit'
      preLoaderRoute: typeof MatchesMatchIdGamesGameNumberScoresEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminPermissionsRoute: typeof AdminPermissionsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminPermissionsRoute: AdminPermissionsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ConfirmEmailRoute: ConfirmEmailRoute,
  DashboardRoute: DashboardRoute,
  DesignSystemRoute: DesignSystemRoute,
  SettingsRoute: SettingsRoute,
  SimulatorRoute: SimulatorRoute,
  LoginSentRoute: LoginSentRoute,
  LoginVerifyingRoute: LoginVerifyingRoute,
  LoginWelcomeRoute: LoginWelcomeRoute,
  MatchesNewRoute: MatchesNewRoute,
  PlayersUserIdRoute: PlayersUserIdRoute,
  TournamentsTournamentIdRoute: TournamentsTournamentIdRoute,
  LoginIndexRoute: LoginIndexRoute,
  MatchesIndexRoute: MatchesIndexRoute,
  PlayersIndexRoute: PlayersIndexRoute,
  TournamentsIndexRoute: TournamentsIndexRoute,
  PMatchesMatchIdRoute: PMatchesMatchIdRoute,
  PPlayersUsernameRoute: PPlayersUsernameRoute,
  MatchesMatchIdIndexRoute: MatchesMatchIdIndexRoute,
  MatchesMatchIdGamesGameNumberScoresEditRoute:
    MatchesMatchIdGamesGameNumberScoresEditRoute,
  MatchesMatchIdGamesGameNumberScoresNewRoute:
    MatchesMatchIdGamesGameNumberScoresNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
