/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as ConfirmEmailRouteImport } from './routes/confirm-email'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login.index'
import { Route as LoginWelcomeRouteImport } from './routes/login.welcome'
import { Route as LoginVerifyingRouteImport } from './routes/login.verifying'
import { Route as LoginSentRouteImport } from './routes/login.sent'
import { Route as AppTournamentsRouteImport } from './routes/_app/tournaments'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppTournamentsIndexRouteImport } from './routes/_app/tournaments/index'
import { Route as AppPlayersIndexRouteImport } from './routes/_app/players/index'
import { Route as AppNotificationsIndexRouteImport } from './routes/_app/notifications.index'
import { Route as AppMatchesIndexRouteImport } from './routes/_app/matches/index'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin.index'
import { Route as AppTournamentsTournamentIdRouteImport } from './routes/_app/tournaments.$tournamentId'
import { Route as AppPlayersUserIdRouteImport } from './routes/_app/players/$userId'
import { Route as AppNotificationsSettingsRouteImport } from './routes/_app/notifications.settings'
import { Route as AppMatchesNewRouteImport } from './routes/_app/matches/new'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin.users'
import { Route as AppAdminRolesRouteImport } from './routes/_app/admin.roles'
import { Route as AppAdminPermissionsRouteImport } from './routes/_app/admin.permissions'
import { Route as AppAdminBroadcastRouteImport } from './routes/_app/admin.broadcast'
import { Route as AppMatchesMatchIdIndexRouteImport } from './routes/_app/matches.$matchId.index'
import { Route as AppMatchesMatchIdResultsNewRouteImport } from './routes/_app/matches.$matchId.results.new'
import { Route as AppMatchesMatchIdGamesGameNumberScoresNewRouteImport } from './routes/_app/matches.$matchId.games.$gameNumber.scores.new'
import { Route as AppMatchesMatchIdGamesGameNumberScoresEditRouteImport } from './routes/_app/matches.$matchId.games.$gameNumber.scores.edit'

const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmEmailRoute = ConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginWelcomeRoute = LoginWelcomeRouteImport.update({
  id: '/login/welcome',
  path: '/login/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginVerifyingRoute = LoginVerifyingRouteImport.update({
  id: '/login/verifying',
  path: '/login/verifying',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginSentRoute = LoginSentRouteImport.update({
  id: '/login/sent',
  path: '/login/sent',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTournamentsRoute = AppTournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTournamentsIndexRoute = AppTournamentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTournamentsRoute,
} as any)
const AppPlayersIndexRoute = AppPlayersIndexRouteImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNotificationsIndexRoute = AppNotificationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppNotificationsRoute,
} as any)
const AppMatchesIndexRoute = AppMatchesIndexRouteImport.update({
  id: '/matches/',
  path: '/matches/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppTournamentsTournamentIdRoute =
  AppTournamentsTournamentIdRouteImport.update({
    id: '/$tournamentId',
    path: '/$tournamentId',
    getParentRoute: () => AppTournamentsRoute,
  } as any)
const AppPlayersUserIdRoute = AppPlayersUserIdRouteImport.update({
  id: '/players/$userId',
  path: '/players/$userId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNotificationsSettingsRoute =
  AppNotificationsSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppNotificationsRoute,
  } as any)
const AppMatchesNewRoute = AppMatchesNewRouteImport.update({
  id: '/matches/new',
  path: '/matches/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminRolesRoute = AppAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPermissionsRoute = AppAdminPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminBroadcastRoute = AppAdminBroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppMatchesMatchIdIndexRoute = AppMatchesMatchIdIndexRouteImport.update({
  id: '/matches/$matchId/',
  path: '/matches/$matchId/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMatchesMatchIdResultsNewRoute =
  AppMatchesMatchIdResultsNewRouteImport.update({
    id: '/matches/$matchId/results/new',
    path: '/matches/$matchId/results/new',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppMatchesMatchIdGamesGameNumberScoresNewRoute =
  AppMatchesMatchIdGamesGameNumberScoresNewRouteImport.update({
    id: '/matches/$matchId/games/$gameNumber/scores/new',
    path: '/matches/$matchId/games/$gameNumber/scores/new',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppMatchesMatchIdGamesGameNumberScoresEditRoute =
  AppMatchesMatchIdGamesGameNumberScoresEditRouteImport.update({
    id: '/matches/$matchId/games/$gameNumber/scores/edit',
    path: '/matches/$matchId/games/$gameNumber/scores/edit',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/design-system': typeof DesignSystemRoute
  '/simulator': typeof SimulatorRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/notifications': typeof AppNotificationsRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/tournaments': typeof AppTournamentsRouteWithChildren
  '/login/sent': typeof LoginSentRoute
  '/login/verifying': typeof LoginVerifyingRoute
  '/login/welcome': typeof LoginWelcomeRoute
  '/login/': typeof LoginIndexRoute
  '/admin/broadcast': typeof AppAdminBroadcastRoute
  '/admin/permissions': typeof AppAdminPermissionsRoute
  '/admin/roles': typeof AppAdminRolesRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/matches/new': typeof AppMatchesNewRoute
  '/notifications/settings': typeof AppNotificationsSettingsRoute
  '/players/$userId': typeof AppPlayersUserIdRoute
  '/tournaments/$tournamentId': typeof AppTournamentsTournamentIdRoute
  '/admin/': typeof AppAdminIndexRoute
  '/matches/': typeof AppMatchesIndexRoute
  '/notifications/': typeof AppNotificationsIndexRoute
  '/players/': typeof AppPlayersIndexRoute
  '/tournaments/': typeof AppTournamentsIndexRoute
  '/matches/$matchId/': typeof AppMatchesMatchIdIndexRoute
  '/matches/$matchId/results/new': typeof AppMatchesMatchIdResultsNewRoute
  '/matches/$matchId/games/$gameNumber/scores/edit': typeof AppMatchesMatchIdGamesGameNumberScoresEditRoute
  '/matches/$matchId/games/$gameNumber/scores/new': typeof AppMatchesMatchIdGamesGameNumberScoresNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/design-system': typeof DesignSystemRoute
  '/simulator': typeof SimulatorRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/login/sent': typeof LoginSentRoute
  '/login/verifying': typeof LoginVerifyingRoute
  '/login/welcome': typeof LoginWelcomeRoute
  '/login': typeof LoginIndexRoute
  '/admin/broadcast': typeof AppAdminBroadcastRoute
  '/admin/permissions': typeof AppAdminPermissionsRoute
  '/admin/roles': typeof AppAdminRolesRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/matches/new': typeof AppMatchesNewRoute
  '/notifications/settings': typeof AppNotificationsSettingsRoute
  '/players/$userId': typeof AppPlayersUserIdRoute
  '/tournaments/$tournamentId': typeof AppTournamentsTournamentIdRoute
  '/admin': typeof AppAdminIndexRoute
  '/matches': typeof AppMatchesIndexRoute
  '/notifications': typeof AppNotificationsIndexRoute
  '/players': typeof AppPlayersIndexRoute
  '/tournaments': typeof AppTournamentsIndexRoute
  '/matches/$matchId': typeof AppMatchesMatchIdIndexRoute
  '/matches/$matchId/results/new': typeof AppMatchesMatchIdResultsNewRoute
  '/matches/$matchId/games/$gameNumber/scores/edit': typeof AppMatchesMatchIdGamesGameNumberScoresEditRoute
  '/matches/$matchId/games/$gameNumber/scores/new': typeof AppMatchesMatchIdGamesGameNumberScoresNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/confirm-email': typeof ConfirmEmailRoute
  '/design-system': typeof DesignSystemRoute
  '/simulator': typeof SimulatorRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/notifications': typeof AppNotificationsRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tournaments': typeof AppTournamentsRouteWithChildren
  '/login/sent': typeof LoginSentRoute
  '/login/verifying': typeof LoginVerifyingRoute
  '/login/welcome': typeof LoginWelcomeRoute
  '/login/': typeof LoginIndexRoute
  '/_app/admin/broadcast': typeof AppAdminBroadcastRoute
  '/_app/admin/permissions': typeof AppAdminPermissionsRoute
  '/_app/admin/roles': typeof AppAdminRolesRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/matches/new': typeof AppMatchesNewRoute
  '/_app/notifications/settings': typeof AppNotificationsSettingsRoute
  '/_app/players/$userId': typeof AppPlayersUserIdRoute
  '/_app/tournaments/$tournamentId': typeof AppTournamentsTournamentIdRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/matches/': typeof AppMatchesIndexRoute
  '/_app/notifications/': typeof AppNotificationsIndexRoute
  '/_app/players/': typeof AppPlayersIndexRoute
  '/_app/tournaments/': typeof AppTournamentsIndexRoute
  '/_app/matches/$matchId/': typeof AppMatchesMatchIdIndexRoute
  '/_app/matches/$matchId/results/new': typeof AppMatchesMatchIdResultsNewRoute
  '/_app/matches/$matchId/games/$gameNumber/scores/edit': typeof AppMatchesMatchIdGamesGameNumberScoresEditRoute
  '/_app/matches/$matchId/games/$gameNumber/scores/new': typeof AppMatchesMatchIdGamesGameNumberScoresNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confirm-email'
    | '/design-system'
    | '/simulator'
    | '/admin'
    | '/dashboard'
    | '/notifications'
    | '/settings'
    | '/tournaments'
    | '/login/sent'
    | '/login/verifying'
    | '/login/welcome'
    | '/login/'
    | '/admin/broadcast'
    | '/admin/permissions'
    | '/admin/roles'
    | '/admin/users'
    | '/matches/new'
    | '/notifications/settings'
    | '/players/$userId'
    | '/tournaments/$tournamentId'
    | '/admin/'
    | '/matches/'
    | '/notifications/'
    | '/players/'
    | '/tournaments/'
    | '/matches/$matchId/'
    | '/matches/$matchId/results/new'
    | '/matches/$matchId/games/$gameNumber/scores/edit'
    | '/matches/$matchId/games/$gameNumber/scores/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confirm-email'
    | '/design-system'
    | '/simulator'
    | '/dashboard'
    | '/settings'
    | '/login/sent'
    | '/login/verifying'
    | '/login/welcome'
    | '/login'
    | '/admin/broadcast'
    | '/admin/permissions'
    | '/admin/roles'
    | '/admin/users'
    | '/matches/new'
    | '/notifications/settings'
    | '/players/$userId'
    | '/tournaments/$tournamentId'
    | '/admin'
    | '/matches'
    | '/notifications'
    | '/players'
    | '/tournaments'
    | '/matches/$matchId'
    | '/matches/$matchId/results/new'
    | '/matches/$matchId/games/$gameNumber/scores/edit'
    | '/matches/$matchId/games/$gameNumber/scores/new'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/confirm-email'
    | '/design-system'
    | '/simulator'
    | '/_app/admin'
    | '/_app/dashboard'
    | '/_app/notifications'
    | '/_app/settings'
    | '/_app/tournaments'
    | '/login/sent'
    | '/login/verifying'
    | '/login/welcome'
    | '/login/'
    | '/_app/admin/broadcast'
    | '/_app/admin/permissions'
    | '/_app/admin/roles'
    | '/_app/admin/users'
    | '/_app/matches/new'
    | '/_app/notifications/settings'
    | '/_app/players/$userId'
    | '/_app/tournaments/$tournamentId'
    | '/_app/admin/'
    | '/_app/matches/'
    | '/_app/notifications/'
    | '/_app/players/'
    | '/_app/tournaments/'
    | '/_app/matches/$matchId/'
    | '/_app/matches/$matchId/results/new'
    | '/_app/matches/$matchId/games/$gameNumber/scores/edit'
    | '/_app/matches/$matchId/games/$gameNumber/scores/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ConfirmEmailRoute: typeof ConfirmEmailRoute
  DesignSystemRoute: typeof DesignSystemRoute
  SimulatorRoute: typeof SimulatorRoute
  LoginSentRoute: typeof LoginSentRoute
  LoginVerifyingRoute: typeof LoginVerifyingRoute
  LoginWelcomeRoute: typeof LoginWelcomeRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm-email': {
      id: '/confirm-email'
      path: '/confirm-email'
      fullPath: '/confirm-email'
      preLoaderRoute: typeof ConfirmEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/welcome': {
      id: '/login/welcome'
      path: '/login/welcome'
      fullPath: '/login/welcome'
      preLoaderRoute: typeof LoginWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/verifying': {
      id: '/login/verifying'
      path: '/login/verifying'
      fullPath: '/login/verifying'
      preLoaderRoute: typeof LoginVerifyingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/sent': {
      id: '/login/sent'
      path: '/login/sent'
      fullPath: '/login/sent'
      preLoaderRoute: typeof LoginSentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tournaments': {
      id: '/_app/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof AppTournamentsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tournaments/': {
      id: '/_app/tournaments/'
      path: '/'
      fullPath: '/tournaments/'
      preLoaderRoute: typeof AppTournamentsIndexRouteImport
      parentRoute: typeof AppTournamentsRoute
    }
    '/_app/players/': {
      id: '/_app/players/'
      path: '/players'
      fullPath: '/players/'
      preLoaderRoute: typeof AppPlayersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/notifications/': {
      id: '/_app/notifications/'
      path: '/'
      fullPath: '/notifications/'
      preLoaderRoute: typeof AppNotificationsIndexRouteImport
      parentRoute: typeof AppNotificationsRoute
    }
    '/_app/matches/': {
      id: '/_app/matches/'
      path: '/matches'
      fullPath: '/matches/'
      preLoaderRoute: typeof AppMatchesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/tournaments/$tournamentId': {
      id: '/_app/tournaments/$tournamentId'
      path: '/$tournamentId'
      fullPath: '/tournaments/$tournamentId'
      preLoaderRoute: typeof AppTournamentsTournamentIdRouteImport
      parentRoute: typeof AppTournamentsRoute
    }
    '/_app/players/$userId': {
      id: '/_app/players/$userId'
      path: '/players/$userId'
      fullPath: '/players/$userId'
      preLoaderRoute: typeof AppPlayersUserIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/notifications/settings': {
      id: '/_app/notifications/settings'
      path: '/settings'
      fullPath: '/notifications/settings'
      preLoaderRoute: typeof AppNotificationsSettingsRouteImport
      parentRoute: typeof AppNotificationsRoute
    }
    '/_app/matches/new': {
      id: '/_app/matches/new'
      path: '/matches/new'
      fullPath: '/matches/new'
      preLoaderRoute: typeof AppMatchesNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/roles': {
      id: '/_app/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AppAdminRolesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/permissions': {
      id: '/_app/admin/permissions'
      path: '/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AppAdminPermissionsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/broadcast': {
      id: '/_app/admin/broadcast'
      path: '/broadcast'
      fullPath: '/admin/broadcast'
      preLoaderRoute: typeof AppAdminBroadcastRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/matches/$matchId/': {
      id: '/_app/matches/$matchId/'
      path: '/matches/$matchId'
      fullPath: '/matches/$matchId/'
      preLoaderRoute: typeof AppMatchesMatchIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/matches/$matchId/results/new': {
      id: '/_app/matches/$matchId/results/new'
      path: '/matches/$matchId/results/new'
      fullPath: '/matches/$matchId/results/new'
      preLoaderRoute: typeof AppMatchesMatchIdResultsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/matches/$matchId/games/$gameNumber/scores/new': {
      id: '/_app/matches/$matchId/games/$gameNumber/scores/new'
      path: '/matches/$matchId/games/$gameNumber/scores/new'
      fullPath: '/matches/$matchId/games/$gameNumber/scores/new'
      preLoaderRoute: typeof AppMatchesMatchIdGamesGameNumberScoresNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/matches/$matchId/games/$gameNumber/scores/edit': {
      id: '/_app/matches/$matchId/games/$gameNumber/scores/edit'
      path: '/matches/$matchId/games/$gameNumber/scores/edit'
      fullPath: '/matches/$matchId/games/$gameNumber/scores/edit'
      preLoaderRoute: typeof AppMatchesMatchIdGamesGameNumberScoresEditRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminBroadcastRoute: typeof AppAdminBroadcastRoute
  AppAdminPermissionsRoute: typeof AppAdminPermissionsRoute
  AppAdminRolesRoute: typeof AppAdminRolesRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminBroadcastRoute: AppAdminBroadcastRoute,
  AppAdminPermissionsRoute: AppAdminPermissionsRoute,
  AppAdminRolesRoute: AppAdminRolesRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppNotificationsRouteChildren {
  AppNotificationsSettingsRoute: typeof AppNotificationsSettingsRoute
  AppNotificationsIndexRoute: typeof AppNotificationsIndexRoute
}

const AppNotificationsRouteChildren: AppNotificationsRouteChildren = {
  AppNotificationsSettingsRoute: AppNotificationsSettingsRoute,
  AppNotificationsIndexRoute: AppNotificationsIndexRoute,
}

const AppNotificationsRouteWithChildren =
  AppNotificationsRoute._addFileChildren(AppNotificationsRouteChildren)

interface AppTournamentsRouteChildren {
  AppTournamentsTournamentIdRoute: typeof AppTournamentsTournamentIdRoute
  AppTournamentsIndexRoute: typeof AppTournamentsIndexRoute
}

const AppTournamentsRouteChildren: AppTournamentsRouteChildren = {
  AppTournamentsTournamentIdRoute: AppTournamentsTournamentIdRoute,
  AppTournamentsIndexRoute: AppTournamentsIndexRoute,
}

const AppTournamentsRouteWithChildren = AppTournamentsRoute._addFileChildren(
  AppTournamentsRouteChildren,
)

interface AppRouteRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppNotificationsRoute: typeof AppNotificationsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppTournamentsRoute: typeof AppTournamentsRouteWithChildren
  AppMatchesNewRoute: typeof AppMatchesNewRoute
  AppPlayersUserIdRoute: typeof AppPlayersUserIdRoute
  AppMatchesIndexRoute: typeof AppMatchesIndexRoute
  AppPlayersIndexRoute: typeof AppPlayersIndexRoute
  AppMatchesMatchIdIndexRoute: typeof AppMatchesMatchIdIndexRoute
  AppMatchesMatchIdResultsNewRoute: typeof AppMatchesMatchIdResultsNewRoute
  AppMatchesMatchIdGamesGameNumberScoresEditRoute: typeof AppMatchesMatchIdGamesGameNumberScoresEditRoute
  AppMatchesMatchIdGamesGameNumberScoresNewRoute: typeof AppMatchesMatchIdGamesGameNumberScoresNewRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppNotificationsRoute: AppNotificationsRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppTournamentsRoute: AppTournamentsRouteWithChildren,
  AppMatchesNewRoute: AppMatchesNewRoute,
  AppPlayersUserIdRoute: AppPlayersUserIdRoute,
  AppMatchesIndexRoute: AppMatchesIndexRoute,
  AppPlayersIndexRoute: AppPlayersIndexRoute,
  AppMatchesMatchIdIndexRoute: AppMatchesMatchIdIndexRoute,
  AppMatchesMatchIdResultsNewRoute: AppMatchesMatchIdResultsNewRoute,
  AppMatchesMatchIdGamesGameNumberScoresEditRoute:
    AppMatchesMatchIdGamesGameNumberScoresEditRoute,
  AppMatchesMatchIdGamesGameNumberScoresNewRoute:
    AppMatchesMatchIdGamesGameNumberScoresNewRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  ConfirmEmailRoute: ConfirmEmailRoute,
  DesignSystemRoute: DesignSystemRoute,
  SimulatorRoute: SimulatorRoute,
  LoginSentRoute: LoginSentRoute,
  LoginVerifyingRoute: LoginVerifyingRoute,
  LoginWelcomeRoute: LoginWelcomeRoute,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
