/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session Endpoint */
        get: operations["get_session_endpoint_v1_session_get"];
        put?: never;
        post?: never;
        /**
         * Delete Session Endpoint
         * @description Sign the caller out *of this browser*. Revokes the token row tied to
         *     the current cookie (other devices keep their own tokens) and clears the
         *     cookie. Idempotent — a missing or already-invalid cookie still 204s and
         *     clears whatever the browser is holding.
         */
        delete: operations["delete_session_endpoint_v1_session_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Current User */
        patch: operations["update_current_user_v1_me_patch"];
        trace?: never;
    };
    "/v1/me/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Email */
        post: operations["set_email_v1_me_email_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/email/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resend Email Confirmation */
        post: operations["resend_email_confirmation_v1_me_email_resend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/email/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm Email
         * @description Consume an email-change token: stamp the new email + ``confirmed_at``.
         *
         *     Invariant: ``user.email`` holds the prior confirmed address; the new
         *     address lives on ``token.sent_to`` until this endpoint runs. This is
         *     the single place either column flips.
         *
         *     The token in the email is itself the bearer credential — we don't
         *     require the click to come from the same browser that requested it.
         *     That lets users complete the flow on a mobile mail client even when
         *     their desktop session cookie isn't available, and avoids minting an
         *     orphan guest user on every cross-device click. The endpoint also
         *     rotates the caller's session cookie to the token's owner so the
         *     confirming browser ends up signed in as the right user.
         *
         *     A *merge* token (``merge:<uuid>``) is handled separately: instead of
         *     stamping an address onto the guest that requested it, the guest is folded
         *     into the account that owns the address and the caller is signed in as that
         *     account. See ``_confirm_account_merge``.
         */
        post: operations["confirm_email_v1_me_email_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/login/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Login Email
         * @description Mint a magic-link sign-in token and email it.
         *
         *     Always returns the same 202 shape regardless of whether the address
         *     belongs to a known account. Differential responses would let an
         *     attacker enumerate the user base by cycling guest sessions for fresh
         *     rate-limit budgets — the same enumeration vector the email-change flow
         *     guards against.
         *
         *     Accounts whose email hasn't been confirmed yet get the confirmation
         *     link re-sent instead of a sign-in link. The login token would let
         *     someone sign in without proving control of the inbox; the confirmation
         *     link clears that hurdle and (per ``confirm_email``) rotates them into
         *     a session anyway.
         *
         *     Records the requesting browser's guest on the token so the merge it drives
         *     is token-bound (follows the guest cross-device), mirroring the settings
         *     merge flow.
         */
        post: operations["request_login_email_v1_login_request_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/login/consume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Consume Login Token
         * @description Verify a magic-link token and rotate the caller's session cookie.
         *
         *     The token is itself the bearer credential, so the click is accepted from
         *     any browser — the inbox proves ownership of the email. The endpoint
         *     rotates the caller's session cookie to the token's owner regardless of
         *     which guest session (if any) the browser arrived with.
         */
        post: operations["consume_login_token_v1_login_consume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/merge/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Merge
         * @description Side-effect-free look at an emailed link before it's consumed, so the
         *     client can show a "bring N matches over?" confirmation. Never consumes,
         *     rotates, or merges — a wrong/expired token simply returns ``is_merge=False``
         *     and the client finalizes through the real confirm/consume endpoint.
         *
         *     Safe to return usernames + counts: the 256-bit token is the bearer
         *     credential, so only someone holding the link can ask.
         */
        post: operations["preview_merge_v1_merge_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Permissions */
        get: operations["list_permissions_v1_permissions_get"];
        put?: never;
        /** Create Permission */
        post: operations["create_permission_v1_permissions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/permissions/{permission_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Permission */
        get: operations["get_permission_v1_permissions__permission_id__get"];
        put?: never;
        post?: never;
        /** Delete Permission */
        delete: operations["delete_permission_v1_permissions__permission_id__delete"];
        options?: never;
        head?: never;
        /** Update Permission */
        patch: operations["update_permission_v1_permissions__permission_id__patch"];
        trace?: never;
    };
    "/v1/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Roles */
        get: operations["list_roles_v1_roles_get"];
        put?: never;
        /** Create Role */
        post: operations["create_role_v1_roles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/roles/{role_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Role */
        get: operations["get_role_v1_roles__role_id__get"];
        put?: never;
        post?: never;
        /** Delete Role */
        delete: operations["delete_role_v1_roles__role_id__delete"];
        options?: never;
        head?: never;
        /** Update Role */
        patch: operations["update_role_v1_roles__role_id__patch"];
        trace?: never;
    };
    "/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_v1_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_v1_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User */
        get: operations["get_user_v1_users__user_id__get"];
        put?: never;
        post?: never;
        /** Delete User */
        delete: operations["delete_user_v1_users__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{user_id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set User Roles */
        put: operations["set_user_roles_v1_users__user_id__roles_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Matches */
        get: operations["list_matches_v1_matches_get"];
        put?: never;
        /** Create Match */
        post: operations["create_match_v1_matches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matches.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Matches Csv
         * @description CSV export of the whole filtered match set (every match, not paginated),
         *     served as an attachment so the browser downloads it directly.
         */
        get: operations["export_matches_csv_v1_matches_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matches/{match_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Match
         * @description Open to anyone, signed in or not. The same endpoint backs both the
         *     authed `/matches/$matchId` route and the public `/p/matches/$matchId`
         *     share route — a signed-in caller gets is_current_user / can_score flags;
         *     an anonymous caller gets the same view with those flags off. Per-IP
         *     rate-limited (60/min) so an open URL can't be scraped from one source.
         *
         *     The serializer flags whether the current user is on a side; write paths
         *     below still gate on participation via `get_current_user`.
         */
        get: operations["get_match_v1_matches__match_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matches/{match_id}/games/{game_number}/scores/new": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Game Score */
        post: operations["create_game_score_v1_matches__match_id__games__game_number__scores_new_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matches/{match_id}/games/{game_number}/scores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Game Score */
        put: operations["update_game_score_v1_matches__match_id__games__game_number__scores_put"];
        post?: never;
        /** Delete Game Score */
        delete: operations["delete_game_score_v1_matches__match_id__games__game_number__scores_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matches/{match_id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Match Result
         * @description Post the result of a match. Any previously-saved per-game scores are
         *     discarded; the payload's games (validated as a complete, decided match)
         *     become canon, and the caller's signature is recorded.
         *
         *     For a non-solo match the status stays ``in_progress`` until every side
         *     signs — the other side acts on the posted result via ``POST /confirmation``
         *     or ``POST /dispute``, and the rating update fires inside /confirmation
         *     when the final signature lands. Solo matches (one side player-less)
         *     finalize immediately here, since there's no second party to attest.
         */
        post: operations["post_match_result_v1_matches__match_id__results_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matches/{match_id}/confirmation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm Match Result
         * @description Sign off on a posted result. When this is the last signature needed
         *     (every side has at least one signing player) the match flips to
         *     ``completed`` and the rating update runs — exactly once.
         */
        post: operations["confirm_match_result_v1_matches__match_id__confirmation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matches/{match_id}/dispute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dispute Match Result
         * @description Reject a posted result. Every signature is cleared and the side
         *     win flags reset to ``None``; the canonical score rows themselves stay in
         *     place so the disputer can navigate to the contested game and PUT a
         *     corrected score. The per-game endpoints unblock automatically once
         *     signatures are empty (see ``_enforce_scorable``).
         */
        post: operations["dispute_match_result_v1_matches__match_id__dispute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/players/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Recent Opponents
         * @description Opponents to feature in the new-match picker.
         *
         *     Ranked by how recently the caller last played them (most recent first).
         *     A player with little or no match history is backfilled with other
         *     registered users, alphabetically, so the list is never short or empty.
         */
        get: operations["list_recent_opponents_v1_players_recent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/players/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Players
         * @description Username substring search backing the opponent typeahead.
         *
         *     Case-insensitive, excludes the caller, and caps the result count so the
         *     client never has to fetch and filter the whole roster. An empty query
         *     matches nothing.
         */
        get: operations["search_players_v1_players_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Players
         * @description Paginated roster backing the `/players` list page.
         *
         *     Sorted by default-league rating (highest first), with NULL ratings (i.e.
         *     players who haven't played a rated match yet) sorted last so the top of
         *     the list always shows ranked players. Falls back to alphabetic order for
         *     ties.
         */
        get: operations["list_players_v1_players_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/players/{player_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Player
         * @description Authed profile bundle for `/players/$userId` — hero + first page of
         *     matches in one response.
         */
        get: operations["get_player_v1_players__player_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/p/players/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Public Player
         * @description Public profile bundle for `/p/players/$username` — same shape as
         *     the authed endpoint. No session required, rate-limited per-IP.
         */
        get: operations["get_public_player_v1_p_players__username__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/players/{player_id}/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Player Matches
         * @description Paginated per-player match history backing the profile-page match
         *     table on BOTH the authed (`/players/$userId`) and public
         *     (`/p/players/$username`) surfaces — the public page has already
         *     resolved username → id via `/v1/p/players/{username}`, so it has the
         *     id to hit this endpoint with.
         *
         *     Public — no session required, IP-rate-limited (60/min) so the match
         *     history can't be scraped from a single source. Newest-first by
         *     ``created_at``. Sets are projected from the player's perspective so
         *     the FE renders them without flipping sides.
         */
        get: operations["list_player_matches_v1_players__player_id__matches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard */
        get: operations["get_dashboard_v1_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/device-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Device Token */
        post: operations["register_device_token_v1_device_tokens_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notifications/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Test Notification */
        post: operations["send_test_notification_v1_notifications_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ComponentHealth */
        ComponentHealth: {
            /** Healthy */
            healthy: boolean;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Error */
            error?: string | null;
        };
        /** ConfirmEmailRequest */
        ConfirmEmailRequest: {
            /** Token */
            token: string;
            /**
             * Skip Merge
             * @default false
             */
            skip_merge: boolean;
        };
        /** ConsumeLoginRequest */
        ConsumeLoginRequest: {
            /** Token */
            token: string;
            /**
             * Skip Merge
             * @default false
             */
            skip_merge: boolean;
        };
        /** DashboardNextMatch */
        DashboardNextMatch: {
            /**
             * Match Id
             * Format: uuid
             */
            match_id: string;
            /** Opponent Username */
            opponent_username: string | null;
            /** Best Of */
            best_of: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * DashboardRating
         * @description Per-league rating snapshot for the dashboard RatingCard.
         *
         *     Emitted only when the user has a rated row in an automatic-strategy league
         *     (Glicko-2 today). Manual leagues and unrated users get ``rating: None``.
         */
        DashboardRating: {
            /**
             * League Id
             * Format: uuid
             */
            league_id: string;
            /** League Name */
            league_name: string;
            /** Strategy Key */
            strategy_key: string;
            /** Current */
            current: number;
            /** Delta */
            delta: number;
            /** Peak */
            peak: number;
            /** Percentile */
            percentile: number | null;
            /** Spark Data */
            spark_data: number[];
            streak: components["schemas"]["DashboardStreak"] | null;
            /** Stats */
            stats: components["schemas"]["DashboardRatingStat"][];
        };
        /**
         * DashboardRatingStat
         * @description Strategy-specific tile in the rating card's stats grid.
         *
         *     Pre-formatted server-side so the frontend doesn't need to know which
         *     fields a strategy emits (Glicko-2's ``rd``/``volatility`` vs whatever a
         *     future Elo/TrueSkill row carries).
         */
        DashboardRatingStat: {
            /** Label */
            label: string;
            /** Value */
            value: string;
        };
        /** DashboardRecentResult */
        DashboardRecentResult: {
            /**
             * Match Id
             * Format: uuid
             */
            match_id: string;
            /** Opponent Username */
            opponent_username: string | null;
            /** Is Win */
            is_win: boolean;
            /** My Games Won */
            my_games_won: number;
            /** Opponent Games Won */
            opponent_games_won: number;
            /**
             * Completed At
             * Format: date-time
             */
            completed_at: string;
            my_rating_change?: components["schemas"]["RatingChange"] | null;
        };
        /** DashboardResponse */
        DashboardResponse: {
            /** Score Banners */
            score_banners: components["schemas"]["DashboardScoreBanner"][];
            next_match: components["schemas"]["DashboardNextMatch"] | null;
            /** Recent Results */
            recent_results: components["schemas"]["DashboardRecentResult"][];
            rating?: components["schemas"]["DashboardRating"] | null;
            /** Completed Match Count */
            completed_match_count: number;
        };
        /** DashboardScoreBanner */
        DashboardScoreBanner: {
            /**
             * Match Id
             * Format: uuid
             */
            match_id: string;
            /** Opponent Username */
            opponent_username: string | null;
            /** Current Game Number */
            current_game_number: number;
        };
        /** DashboardStreak */
        DashboardStreak: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "W" | "L";
            /** N */
            n: number;
        };
        /**
         * DeviceTokenResponse
         * @description Confirmation that the device token is registered to the current user.
         */
        DeviceTokenResponse: {
            /**
             * Registered
             * @default true
             */
            registered: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            redis: components["schemas"]["ComponentHealth"];
            database: components["schemas"]["ComponentHealth"];
            solver: components["schemas"]["ComponentHealth"];
        };
        /**
         * LoginRequestAccepted
         * @description 202 body for the magic-link request endpoint. Always echoes the
         *     submitted address — identical whether or not it maps to a real account,
         *     so the response leaks nothing about which addresses are registered.
         */
        LoginRequestAccepted: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /**
         * MatchCreate
         * @description Request body for ``POST /v1/matches``.
         *
         *     ``opponent_user_id`` is optional: a solo match (the client submits one
         *     when the user starts without picking an opponent) gets a player-less
         *     sentinel opponent side — so it's still scorable — and is always unrated,
         *     since the rating system needs two registered sides.
         *
         *     ``league_id`` is optional: when omitted the server binds the match to the
         *     default league (see ``app.leagues.get_default_league``).
         */
        MatchCreate: {
            /** Opponent User Id */
            opponent_user_id?: string | null;
            /** League Id */
            league_id?: string | null;
            /**
             * Best Of
             * @description Total games to play; one of 1, 3, 5, 7.
             */
            best_of: number;
            /**
             * Rated
             * @default true
             */
            rated: boolean;
        };
        /** MatchDetailsCurrentGame */
        MatchDetailsCurrentGame: {
            /** Game Number */
            game_number: number;
        };
        /**
         * MatchDetailsFormResult
         * @description One past completed match for the Players & form recent-results list.
         *
         *     Counts are framed from the cited *player's* perspective, not from a
         *     side number in the past match.
         */
        MatchDetailsFormResult: {
            /**
             * Match Id
             * Format: uuid
             */
            match_id: string;
            /** Is Win */
            is_win: boolean;
            /** Player Games Won */
            player_games_won: number;
            /** Opponent Games Won */
            opponent_games_won: number;
            /** Opponent Username */
            opponent_username: string | null;
            /**
             * Completed At
             * Format: date-time
             */
            completed_at: string;
        };
        /** MatchDetailsGame */
        MatchDetailsGame: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Game Number */
            game_number: number;
            score: components["schemas"]["MatchDetailsScore"] | null;
        };
        /**
         * MatchDetailsH2H
         * @description Head-to-head between this match's two singles players. Wins are
         *     counted against this match's side numbers (not the side numbers of the
         *     historical matches).
         */
        MatchDetailsH2H: {
            /** Total Meetings */
            total_meetings: number;
            /** Side 1 Wins */
            side_1_wins: number;
            /** Side 2 Wins */
            side_2_wins: number;
            /** Recent Meetings */
            recent_meetings: components["schemas"]["MatchDetailsH2HMeeting"][];
        };
        /**
         * MatchDetailsH2HMeeting
         * @description One past meeting between the two players in *this* match. Game counts
         *     are aligned to this match's side numbers so the FE doesn't need to
         *     re-map per row.
         */
        MatchDetailsH2HMeeting: {
            /**
             * Match Id
             * Format: uuid
             */
            match_id: string;
            /**
             * Completed At
             * Format: date-time
             */
            completed_at: string;
            /** Side 1 Games Won */
            side_1_games_won: number;
            /** Side 2 Games Won */
            side_2_games_won: number;
            /** Winner Side Number */
            winner_side_number: number | null;
        };
        /** MatchDetailsPlayer */
        MatchDetailsPlayer: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Username */
            username: string;
            /** Is Current User */
            is_current_user: boolean;
        };
        /**
         * MatchDetailsPlayerForm
         * @description A player's previous-5 results, attached by ``user_id`` so the FE can
         *     map it onto whichever side carries that user.
         *
         *     All `*_before` fields are anchored to this match's `created_at` — they
         *     describe the player's rating + record going into this match, not after.
         */
        MatchDetailsPlayerForm: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Recent Results */
            recent_results: components["schemas"]["MatchDetailsFormResult"][];
            /** Rating Before */
            rating_before?: number | null;
            /** Rating History */
            rating_history?: number[];
            /**
             * Career Matches Before
             * @default 0
             */
            career_matches_before: number;
            /**
             * Career Wins Before
             * @default 0
             */
            career_wins_before: number;
        };
        /** MatchDetailsScore */
        MatchDetailsScore: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Side 1 Points */
            side_1_points: number;
            /** Side 2 Points */
            side_2_points: number;
            /** Winner Side Number */
            winner_side_number: number;
        };
        /** MatchDetailsSide */
        MatchDetailsSide: {
            /** Side Number */
            side_number: number;
            /** Players */
            players: components["schemas"]["MatchDetailsPlayer"][];
            /** Games Won */
            games_won: number;
            /** Won */
            won: boolean | null;
            /** Is Current User Side */
            is_current_user_side: boolean;
            rating_change?: components["schemas"]["RatingChange"] | null;
        };
        /** MatchGameScoreWrite */
        MatchGameScoreWrite: {
            /** Side 1 Points */
            side_1_points: number;
            /** Side 2 Points */
            side_2_points: number;
        };
        /** MatchLeague */
        MatchLeague: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** MatchListResponse */
        MatchListResponse: {
            /** Items */
            items: components["schemas"]["MatchListRow"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
            /** Status Counts */
            status_counts: {
                [key: string]: number;
            };
        };
        /** MatchListRow */
        MatchListRow: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            status: components["schemas"]["MatchStatus"];
            /** Status Label */
            status_label: string;
            league: components["schemas"]["MatchLeague"];
            /** Sides */
            sides: components["schemas"]["MatchDetailsSide"][];
            /** Best Of */
            best_of: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current Game Number */
            current_game_number: number | null;
            /** Can Score */
            can_score: boolean;
            /** Can Confirm */
            can_confirm: boolean;
        };
        /**
         * MatchResultsGameWrite
         * @description One game inside a finalize-the-match payload. Per-game point legality
         *     is checked here; cross-game checks (contiguous numbering, decided result,
         *     no scores past the decider) live in the handler against the full list.
         */
        MatchResultsGameWrite: {
            /** Game Number */
            game_number: number;
            /** Side 1 Points */
            side_1_points: number;
            /** Side 2 Points */
            side_2_points: number;
        };
        /**
         * MatchResultsWrite
         * @description Request body for ``POST /v1/matches/{match_id}/results``. The list is
         *     canon: the handler deletes every existing game + score on the match and
         *     re-inserts these rows. No merge.
         */
        MatchResultsWrite: {
            /** Games */
            games: components["schemas"]["MatchResultsGameWrite"][];
        };
        /**
         * MatchSignatureView
         * @description One participant's sign-off on the posted result. Surfaced on
         *     ``MatchDetails`` so the FE can render "Awaiting <opponent>'s confirmation"
         *     without joining client-side.
         */
        MatchSignatureView: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Signed At
             * Format: date-time
             */
            signed_at: string;
        };
        /**
         * MatchStatus
         * @enum {string}
         */
        MatchStatus: "pending" | "in_progress" | "completed" | "disputed" | "voided";
        /**
         * MergePreview
         * @description Side-effect-free look at an emailed link before it's consumed, so the
         *     client can decide whether to show a "bring N matches over?" confirmation.
         *
         *     ``is_merge`` is true only for a link that would fold a guest into another
         *     account (a settings merge token, or a sign-in token that recorded a
         *     requesting guest). The client shows the gate only when there are matches to
         *     carry (``guest_matches_count > 0``); otherwise it finalizes silently.
         */
        MergePreview: {
            /** Is Merge */
            is_merge: boolean;
            /** Owner Username */
            owner_username?: string | null;
            /** Guest Username */
            guest_username?: string | null;
            /**
             * Guest Matches Count
             * @default 0
             */
            guest_matches_count: number;
        };
        /** MergePreviewRequest */
        MergePreviewRequest: {
            /** Token */
            token: string;
        };
        /**
         * MergeSummary
         * @description Reported by sign-in / email-confirm responses when the call merged the
         *     caller's ephemeral session into a different (verified) account. Drives the
         *     "we brought your N matches with you" toast.
         */
        MergeSummary: {
            /** Matches Moved */
            matches_moved: number;
        };
        /** PermissionCreate */
        PermissionCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /** PermissionRead */
        PermissionRead: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PermissionUpdate */
        PermissionUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
        };
        /**
         * PlayerDetail
         * @description Profile-page bundle: the hero (`PlayerSummary` fields) plus the
         *     first page of matches inline. Saves a round trip on initial load —
         *     `GET /v1/players/{id}` (and the public `/v1/p/players/{username}`
         *     variant) returns this so the profile page paints with one request.
         *
         *     Pagination beyond page 1 still hits `GET /v1/players/{id}/matches`
         *     directly; the FE seeds page 1's cache from this `matches` field via
         *     TanStack Query's `initialData`.
         */
        PlayerDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Username */
            username: string;
            /** Rating */
            rating?: number | null;
            /**
             * Wins
             * @default 0
             */
            wins: number;
            /**
             * Losses
             * @default 0
             */
            losses: number;
            /**
             * Form
             * @default
             */
            form: string;
            matches: components["schemas"]["PlayerMatchListResponse"];
        };
        /**
         * PlayerListResponse
         * @description Paginated `/v1/players` response backing the `/players` list page.
         */
        PlayerListResponse: {
            /** Items */
            items: components["schemas"]["PlayerSummary"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /**
         * PlayerMatchListResponse
         * @description Paginated per-player match list backing the profile page's match
         *     table.
         */
        PlayerMatchListResponse: {
            /** Items */
            items: components["schemas"]["PlayerMatchRow"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /**
         * PlayerMatchOpponent
         * @description Compact opponent shape for a per-player match row. ``id`` and
         *     ``username`` are both ``None`` for the player-less sentinel side
         *     ("No opponent" matches).
         */
        PlayerMatchOpponent: {
            /** Id */
            id?: string | null;
            /** Username */
            username?: string | null;
        };
        /**
         * PlayerMatchRow
         * @description A single row in the per-player match list. Pre-shaped so the FE doesn't
         *     have to join sides + games + flip perspective.
         */
        PlayerMatchRow: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            status: components["schemas"]["MatchStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            opponent: components["schemas"]["PlayerMatchOpponent"];
            /** Sets */
            sets: components["schemas"]["PlayerMatchSet"][];
            /** Result */
            result?: ("W" | "L") | null;
        };
        /**
         * PlayerMatchSet
         * @description A single game's score from the headline player's perspective.
         */
        PlayerMatchSet: {
            /** Mine */
            mine: number;
            /** Theirs */
            theirs: number;
        };
        /**
         * PlayerRead
         * @description A user the current player can pick as a match opponent.
         *
         *     Used by the typeahead/opponent picker. ``rating`` is the player's current
         *     ``rating_value`` in the league the request was scoped to (defaulting to
         *     the default league) — None if they haven't yet played a rated match in
         *     that league or, for manual-strategy leagues, haven't been imported.
         */
        PlayerRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Username */
            username: string;
            /** Rating */
            rating?: number | null;
        };
        /**
         * PlayerSummary
         * @description Pre-shaped for the `/players` list and the profile-page hero.
         *
         *     Carries everything those surfaces render: the username + the default-
         *     league rating + a career W-L from completed matches + a 5-character form
         *     string (newest first) so the UI can render the form-dots without a
         *     follow-up query.
         */
        PlayerSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Username */
            username: string;
            /** Rating */
            rating?: number | null;
            /**
             * Wins
             * @default 0
             */
            wins: number;
            /**
             * Losses
             * @default 0
             */
            losses: number;
            /**
             * Form
             * @default
             */
            form: string;
        };
        /**
         * RatingChange
         * @description A user's rating delta on a single completed match.
         */
        RatingChange: {
            /** Before */
            before: number | null;
            /** After */
            after: number;
            /** Delta */
            delta: number;
        };
        /** RbacUserCreate */
        RbacUserCreate: {
            /** Username */
            username: string;
        };
        /** RbacUserRead */
        RbacUserRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Username */
            username: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Role Ids */
            role_ids: string[];
        };
        /** RbacUserRolesUpdate */
        RbacUserRolesUpdate: {
            /** Role Ids */
            role_ids: string[];
        };
        /**
         * RegisterDeviceTokenRequest
         * @description An installed iOS app registering its APNs device token against the
         *     caller's session, so the backend can push to it later.
         */
        RegisterDeviceTokenRequest: {
            /** Token */
            token: string;
            /**
             * Platform
             * @constant
             */
            platform: "ios";
            /**
             * Environment
             * @enum {string}
             */
            environment: "sandbox" | "production";
        };
        /** RequestLoginRequest */
        RequestLoginRequest: {
            /** Captcha Token */
            captcha_token: string;
            /**
             * Fmm Hp Token
             * @default
             */
            fmm_hp_token: string;
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** ResendEmailRequest */
        ResendEmailRequest: {
            /** Captcha Token */
            captcha_token: string;
            /**
             * Fmm Hp Token
             * @default
             */
            fmm_hp_token: string;
        };
        /** RoleCreate */
        RoleCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Template Id */
            template_id?: string | null;
            /** Permission Ids */
            permission_ids?: string[] | null;
        };
        /** RoleRead */
        RoleRead: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Permission Ids */
            permission_ids: string[];
        };
        /** RoleUpdate */
        RoleUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Permission Ids */
            permission_ids?: string[] | null;
        };
        /** Scoreboard */
        Scoreboard: {
            status: components["schemas"]["Status"];
        };
        /** SessionData */
        SessionData: {
            user: components["schemas"]["SessionUser"];
        };
        /** SessionResponse */
        SessionResponse: {
            data: components["schemas"]["SessionData"];
            merged?: components["schemas"]["MergeSummary"] | null;
        };
        /** SessionUser */
        SessionUser: {
            /** Username */
            username: string;
            /** Permissions */
            permissions: string[];
            /** Email */
            email?: string | null;
            /** Confirmed At */
            confirmed_at?: string | null;
            /** Pending Email */
            pending_email?: string | null;
        };
        /** SetEmailRequest */
        SetEmailRequest: {
            /** Captcha Token */
            captcha_token: string;
            /**
             * Fmm Hp Token
             * @default
             */
            fmm_hp_token: string;
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /**
         * Status
         * @enum {string}
         */
        Status: "scheduled" | "live" | "final";
        /**
         * TestNotificationResponse
         * @description Outcome of firing a test push to the current user's devices.
         *
         *     ``sent`` counts deliveries APNs accepted; ``pruned`` counts tokens APNs
         *     reported as gone (unregistered / bad), which are deleted as a side effect.
         */
        TestNotificationResponse: {
            /** Sent */
            sent: number;
            /** Pruned */
            pruned: number;
        };
        /** UpdateCurrentUserRequest */
        UpdateCurrentUserRequest: {
            /** Username */
            username: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** MatchDetails */
        app__schemas__match__MatchDetails: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            status: components["schemas"]["MatchStatus"];
            /** Status Label */
            status_label: string;
            league: components["schemas"]["MatchLeague"];
            /** Best Of */
            best_of: number;
            /** Games To Win */
            games_to_win: number;
            /** Team Size */
            team_size: number;
            /** Affects Rating */
            affects_rating: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Sides */
            sides: components["schemas"]["MatchDetailsSide"][];
            /** Games */
            games: components["schemas"]["MatchDetailsGame"][];
            current_game: components["schemas"]["MatchDetailsCurrentGame"] | null;
            /** Can Score */
            can_score: boolean;
            /** Can Finalize */
            can_finalize: boolean;
            /** Can Confirm */
            can_confirm: boolean;
            /** Signatures */
            signatures: components["schemas"]["MatchSignatureView"][];
            /** Recent Form */
            recent_form?: components["schemas"]["MatchDetailsPlayerForm"][];
            head_to_head?: components["schemas"]["MatchDetailsH2H"] | null;
            data: components["schemas"]["app__schemas__view__match_details__MatchDetails"];
        };
        /** MatchDetails */
        app__schemas__view__match_details__MatchDetails: {
            scoreboard: components["schemas"]["Scoreboard"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_session_endpoint_v1_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_endpoint_v1_session_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_current_user_v1_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCurrentUserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_email_v1_me_email_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetEmailRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resend_email_confirmation_v1_me_email_resend_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResendEmailRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_email_v1_me_email_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmEmailRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_login_email_v1_login_request_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginRequestAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    consume_login_token_v1_login_consume_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsumeLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_merge_v1_merge_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MergePreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MergePreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_permissions_v1_permissions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_permission_v1_permissions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PermissionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_permission_v1_permissions__permission_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                permission_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_permission_v1_permissions__permission_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                permission_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_permission_v1_permissions__permission_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                permission_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PermissionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_roles_v1_roles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_role_v1_roles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_role_v1_roles__role_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_role_v1_roles__role_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_role_v1_roles__role_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_v1_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RbacUserRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_v1_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RbacUserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RbacUserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_v1_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RbacUserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_v1_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_user_roles_v1_users__user_id__roles_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RbacUserRolesUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RbacUserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_matches_v1_matches_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["MatchStatus"] | null;
                q?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_match_v1_matches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__schemas__match__MatchDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_matches_csv_v1_matches_csv_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["MatchStatus"] | null;
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_match_v1_matches__match_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__schemas__match__MatchDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_game_score_v1_matches__match_id__games__game_number__scores_new_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
                game_number: number;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchGameScoreWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__schemas__match__MatchDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_game_score_v1_matches__match_id__games__game_number__scores_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
                game_number: number;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchGameScoreWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__schemas__match__MatchDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_game_score_v1_matches__match_id__games__game_number__scores_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
                game_number: number;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__schemas__match__MatchDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_match_result_v1_matches__match_id__results_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchResultsWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__schemas__match__MatchDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_match_result_v1_matches__match_id__confirmation_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__schemas__match__MatchDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dispute_match_result_v1_matches__match_id__dispute_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__schemas__match__MatchDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_recent_opponents_v1_players_recent_get: {
        parameters: {
            query?: {
                limit?: number;
                league_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_players_v1_players_search_get: {
        parameters: {
            query: {
                /** @description Username substring to match against. */
                q: string;
                limit?: number;
                league_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_players_v1_players_get: {
        parameters: {
            query?: {
                q?: string | null;
                page?: number;
                page_size?: number;
                league_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_v1_players__player_id__get: {
        parameters: {
            query?: {
                league_id?: string | null;
            };
            header?: never;
            path: {
                player_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_public_player_v1_p_players__username__get: {
        parameters: {
            query?: {
                league_id?: string | null;
            };
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_player_matches_v1_players__player_id__matches_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                player_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerMatchListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_v1_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_device_token_v1_device_tokens_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDeviceTokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_test_notification_v1_notifications_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestNotificationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
