#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: ticket #1816 — Stripe test-mode setup for local dev + UAT.
#
# This is a genuine human-prerequisite wizard (Stripe dashboard clicks, a
# local `stripe` CLI login, kubectl access to the UAT cluster) — it blocks
# the Testing stage of #1816, not Implementation. It never touches a LIVE
# key: #1816's server-side sk_live_ startup refusal is the second guard,
# this wizard is the first.
# ──────────────────────────────────────────────────────────────────────────

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
ENV_FILE="$ROOT/.env"

# append_env_list KEY VALUE appends VALUE to KEY's comma-separated list in
# ENV_FILE, deduplicated, preserving order. Unlike write_env (which replaces
# the whole value), STRIPE_WEBHOOK_SIGNING_SECRETS accumulates one entry per
# webhook source (stripe listen for local dev, the permanent UAT endpoint) —
# the app accepts more than one configured secret precisely so adding or
# rotating one never means clobbering another. See .claude/rules/parse-at-boundaries.md.
append_env_list() {
  local key="$1" value="$2" current combined
  current=$(_existing "$key" || true)
  if [[ -z "$current" ]]; then
    combined="$value"
  elif [[ ",$current," == *",$value,"* ]]; then
    combined="$current" # already present, no duplicate
  else
    combined="$current,$value"
  fi
  write_env "$key" "$combined"
}

# refuse_live_key VALUE: stop the wizard cold if a live secret was pasted.
# This wizard only ever configures Stripe TEST mode.
refuse_live_key() {
  local value="$1"
  if [[ "$value" == sk_live_* || "$value" == whsec_live_* ]]; then
    printf '\n  %s✗ that looks like a LIVE key, not a test key.%s\n' "$RED" "$RESET"
    printf '  %sThis wizard only configures Stripe TEST mode. Refusing to continue.%s\n' "$RED" "$RESET"
    exit 1
  fi
}

TOTAL_STAGES=4

banner "Stripe test-mode setup (issue #1816)"

# ── Stage 1: account + test-mode secret key ────────────────────────────────
stage "Stripe: account & test-mode secret key"
say "Fortymm charges into ONE direct Stripe account (Ryan's) at launch."
say "If you don't have a Stripe account yet, create one now — test mode needs"
say "no business verification, so this takes a minute."
open_url "https://dashboard.stripe.com/register"
pause "Account created (or already existed)? Press Enter to continue."

say "Now grab the TEST MODE secret key. Make sure the dashboard's mode toggle"
say "(top left) says \"Test mode\" before copying anything."
open_url "https://dashboard.stripe.com/test/apikeys"
step "Click 'Reveal test key' on the Secret key row, then copy it (starts sk_test_)."
ask_secret STRIPE_SECRET_KEY "Paste the test-mode Secret key:"
refuse_live_key "$STRIPE_SECRET_KEY"
if [[ "$STRIPE_SECRET_KEY" != sk_test_* ]]; then
  warn "that doesn't start with sk_test_ — double check you copied the Secret key, test mode."
fi
write_env STRIPE_SECRET_KEY "$STRIPE_SECRET_KEY"

step "On Settings → Account details, copy your Account ID (starts acct_)."
step "It's the same ID in test and live mode."
open_url "https://dashboard.stripe.com/settings/account"
ask STRIPE_ACCOUNT_ID "Paste the Account ID (acct_...):"
write_env STRIPE_ACCOUNT_ID "$STRIPE_ACCOUNT_ID"

note "At startup the app checks this account owns the configured key, and"
note "refuses to boot on a mismatch or on any sk_live_ key without the"
note "explicit production setting — see api/app/config.py."

# ── Stage 2: local webhook forwarding (Stripe CLI) ─────────────────────────
stage "Local dev: forward webhooks with the Stripe CLI"
if ! command -v stripe >/dev/null 2>&1; then
  warn "the 'stripe' CLI isn't on your PATH."
  open_url "https://docs.stripe.com/stripe-cli"
  say "macOS: brew install stripe/stripe-cli/stripe"
  pause "Press Enter once 'stripe' is installed, or leave it and skip this stage."
fi

if command -v stripe >/dev/null 2>&1; then
  if ! confirm "Already run 'stripe login' for this account?"; then
    say "Run this in another terminal, then come back here:"
    note "    stripe login"
    pause "Press Enter once you're logged in."
  fi

  ask API_PORT_FOR_STRIPE "Local API port to forward webhooks to [8000]:"
  API_PORT_FOR_STRIPE="${API_PORT_FOR_STRIPE:-8000}"

  say "In ANOTHER terminal — leave it running whenever you exercise payments"
  say "locally — start:"
  note "    stripe listen --forward-to localhost:${API_PORT_FOR_STRIPE}/v1/webhooks/stripe"
  say "It prints a line like: \"Your webhook signing secret is whsec_...\"."
  pause "Started it and see the whsec_... line? Press Enter to continue."
  ask_secret STRIPE_LOCAL_WEBHOOK_SECRET "Paste that local whsec_... signing secret:"
  refuse_live_key "$STRIPE_LOCAL_WEBHOOK_SECRET"
  append_env_list STRIPE_WEBHOOK_SIGNING_SECRETS "$STRIPE_LOCAL_WEBHOOK_SECRET"
  note "'stripe listen' mints a new secret each time it starts unless you pass"
  note "--print-secret with a saved value — if webhooks stop verifying, re-run"
  note "this stage to capture the current one."
else
  warn "skipping local webhook forwarding — 'stripe' CLI not found."
  SKIPPED+=("local 'stripe listen' webhook forwarding (install the Stripe CLI, then re-run this wizard)")
fi

# ── Stage 3: permanent UAT test-mode webhook endpoint ──────────────────────
stage "UAT: register the permanent test-mode webhook endpoint"
UAT_WEBHOOK_URL="https://uat.fortymm.com/v1/webhooks/stripe"
say "This registers a real webhook endpoint on your Stripe account (test mode)"
say "pointed at UAT: $UAT_WEBHOOK_URL"
STRIPE_SECRET_KEY_CURRENT=$(_existing STRIPE_SECRET_KEY || true)
if [[ -z "$STRIPE_SECRET_KEY_CURRENT" ]]; then
  warn "no STRIPE_SECRET_KEY found in $ENV_FILE — run stage 1 first."
  SKIPPED+=("UAT webhook endpoint registration (missing STRIPE_SECRET_KEY)")
elif ! command -v python3 >/dev/null 2>&1; then
  warn "python3 not found; this stage parses Stripe's JSON response with it."
  SKIPPED+=("UAT webhook endpoint registration (need python3)")
elif confirm "Register the UAT webhook endpoint now?"; then
  say "Creating the endpoint via the Stripe API..."
  UAT_WEBHOOK_RESPONSE=$(curl -sS "https://api.stripe.com/v1/webhook_endpoints" \
    -u "${STRIPE_SECRET_KEY_CURRENT}:" \
    -d "url=${UAT_WEBHOOK_URL}" \
    -d "enabled_events[]=payment_intent.succeeded" \
    -d "enabled_events[]=payment_intent.payment_failed" \
    -d "enabled_events[]=payment_intent.processing" \
    -d "enabled_events[]=payment_intent.requires_action" \
    -d "enabled_events[]=payment_intent.canceled" \
    -d "enabled_events[]=charge.refunded" \
    -d "description=Fortymm UAT (#1816, test mode)")

  UAT_WEBHOOK_ERROR=$(printf '%s' "$UAT_WEBHOOK_RESPONSE" | python3 -c '
import json, sys
try:
    doc = json.load(sys.stdin)
except ValueError:
    print("could not parse Stripe response as JSON")
    sys.exit(0)
if "error" in doc:
    print(doc["error"].get("message", "unknown Stripe error"))
' || true)

  if [[ -n "$UAT_WEBHOOK_ERROR" ]]; then
    warn "Stripe refused the request: $UAT_WEBHOOK_ERROR"
    SKIPPED+=("UAT webhook endpoint registration ($UAT_WEBHOOK_ERROR)")
  else
    UAT_WEBHOOK_SECRET=$(printf '%s' "$UAT_WEBHOOK_RESPONSE" | python3 -c '
import json, sys
doc = json.load(sys.stdin)
print(doc.get("secret", ""))
')
    UAT_WEBHOOK_ID=$(printf '%s' "$UAT_WEBHOOK_RESPONSE" | python3 -c '
import json, sys
doc = json.load(sys.stdin)
print(doc.get("id", ""))
')
    if [[ -z "$UAT_WEBHOOK_SECRET" ]]; then
      warn "Stripe accepted the endpoint but returned no signing secret — inspect it manually:"
      open_url "https://dashboard.stripe.com/test/webhooks"
      SKIPPED+=("copying the UAT webhook signing secret from the Stripe dashboard")
    else
      say "Registered webhook endpoint $UAT_WEBHOOK_ID."
      append_env_list STRIPE_WEBHOOK_SIGNING_SECRETS "$UAT_WEBHOOK_SECRET"
      note "This secret is shown by Stripe exactly once, at creation — it's now"
      note "saved in $ENV_FILE."
    fi
  fi
else
  say "Skipping — you can re-run this stage later, or create it by hand:"
  open_url "https://dashboard.stripe.com/test/webhooks"
  SKIPPED+=("UAT webhook endpoint registration (skipped)")
fi

# ── Stage 4: sync into the UAT Kubernetes Secret ───────────────────────────
stage "UAT: sync .env into the fortymm-uat-env Secret"
say "This pushes STRIPE_SECRET_KEY, STRIPE_ACCOUNT_ID and"
say "STRIPE_WEBHOOK_SIGNING_SECRETS (plus everything else already in .env)"
say "into the live 'fortymm-uat-env' Secret — the same one scripts/redeploy-uat.sh"
say "syncs on every deploy, so this takes effect without a full redeploy."
if ! command -v kubectl >/dev/null 2>&1; then
  warn "kubectl not found — sync this by hand later:"
  note "    kubectl create secret generic fortymm-uat-env --namespace fortymm-uat \\"
  note "      --from-env-file=.env --dry-run=client -o yaml | kubectl apply -f -"
  SKIPPED+=("syncing .env into the fortymm-uat-env Secret (kubectl missing)")
else
  CURRENT_CONTEXT=$(kubectl config current-context 2>/dev/null || echo "<none>")
  say "Current kubectl context: $CURRENT_CONTEXT"
  if confirm "Is that the fortymm-uat (k3d) cluster? Continue syncing the Secret?"; then
    kubectl create secret generic fortymm-uat-env \
      --namespace fortymm-uat --from-env-file="$ENV_FILE" \
      --dry-run=client -o yaml | kubectl apply -f -
    say "Secret updated. Existing pods keep their OLD environment until restarted:"
    note "    kubectl -n fortymm-uat rollout restart deployment/api deployment/worker"
    if confirm "Restart the api and worker deployments now to pick up the new Secret?"; then
      kubectl -n fortymm-uat rollout restart deployment/api deployment/worker
      say "Restart triggered. Watch it with:"
      note "    kubectl -n fortymm-uat rollout status deployment/api"
    else
      SKIPPED+=("restarting UAT api/worker deployments to pick up the new Secret")
    fi
  else
    warn "wrong context — switch with 'kubectl config use-context <ctx>' and re-run this stage."
    SKIPPED+=("syncing .env into the fortymm-uat-env Secret (wrong kubectl context)")
  fi
fi

finish

say "Reminder: this wizard only ever writes TEST-mode Stripe credentials."
say "Production goes live later, deliberately and separately — #1816's"
say "sk_live_ startup refusal keeps a live key from working until then."
