"""Fresh pre-beta baseline: accounts, durable players, sporting history.

Pre-beta databases are disposable. This revision replaces the previous chain;
there is intentionally no legacy-data upgrade or ID backfill.
"""

from uuid import UUID

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None

NOTIFICATION_TYPE_SEED = [
    (
        "33333333-3333-3333-3333-333333330001",
        "match_reminder",
        "Match reminders",
        "Match",
    ),
    (
        "33333333-3333-3333-3333-333333330002",
        "rating_change",
        "Rating changes",
        "Rating",
    ),
    (
        "33333333-3333-3333-3333-333333330003",
        "tournament",
        "Tournament news",
        "Tourney",
    ),
    (
        "33333333-3333-3333-3333-333333330004",
        "opponent",
        "Challenges & friends",
        "Social",
    ),
    (
        "33333333-3333-3333-3333-333333330005",
        "result_confirm",
        "Score acceptances",
        "Scores",
    ),
    ("33333333-3333-3333-3333-333333330006", "match_calls", "Match calls", "Calls"),
]

NOTIFICATION_CHANNEL_SEED = [
    ("44444444-4444-4444-4444-444444440001", "in_app", "In-app", True),
    ("44444444-4444-4444-4444-444444440002", "push", "Push", True),
    ("44444444-4444-4444-4444-444444440003", "email", "Email", True),
    ("44444444-4444-4444-4444-444444440004", "sms", "SMS", False),
]

DRAW_TYPE_SEED = [
    (
        UUID("22222222-2222-2222-2222-222222220001"),
        "round-robin",
        "Round robin",
        "Everyone in a group plays everyone else in that group. Every "
        "entrant is guaranteed "
        "the same number of matches and the final standings rank the "
        "whole field, so it is "
        "the fairest read on form — but the match count climbs quickly "
        "with group size, and "
        "the event needs at least one group.",
        1,
    ),
    (
        UUID("22222222-2222-2222-2222-222222220002"),
        "single-elim",
        "Single elimination",
        "A knockout bracket: lose once and you are out. It crowns a "
        "champion in the fewest "
        "matches and the least table time, which suits a large field or"
        " a tight schedule — "
        "but half the entrants are finished after one match, and a "
        "field that is not a power "
        "of two gives the top seeds byes.",
        2,
    ),
    (
        UUID("22222222-2222-2222-2222-222222220003"),
        "rr-then-ko",
        "Round-robin then knockout",
        "Groups play all-play-all, then the top finishers from each "
        "group meet in a knockout "
        "bracket.",
        3,
    ),
    (
        UUID("22222222-2222-2222-2222-222222220004"),
        "swiss",
        "Swiss",
        "A fixed number of rounds, each pairing entrants who are on "
        "similar scores. Nobody "
        "is eliminated and everybody plays every round, so a large "
        "field is ranked in far "
        "fewer matches than a round robin — but a round's pairings are "
        "only known once the "
        "round before it has finished, and a long event may repeat a pairing.",
        4,
    ),
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "display_name",
            sa.String(length=255),
            server_default="Account",
            nullable=False,
        ),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("agent_access_linked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("agent_access_revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("merged_into_user_id", sa.UUID(), nullable=True),
        sa.Column("merged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(merged_at IS NULL) = (merged_into_user_id IS NULL)",
            name="ck_accounts_tombstone_pair",
        ),
        sa.CheckConstraint(
            "merged_into_user_id <> id", name="ck_accounts_not_self_merged"
        ),
        sa.ForeignKeyConstraint(
            ["merged_into_user_id"], ["accounts.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_accounts_email"), "accounts", ["email"], unique=True)
    op.create_index(
        op.f("ix_accounts_merged_into_user_id"),
        "accounts",
        ["merged_into_user_id"],
        unique=False,
    )
    op.create_table(
        "draw_types",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("key", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "display_order", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "match_settings",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("team_size", sa.SmallInteger(), nullable=False),
        sa.Column("best_of", sa.SmallInteger(), nullable=False),
        sa.Column(
            "affects_rating",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "verification_policy",
            sa.Enum(
                "none",
                "self_report",
                "opponent_confirms",
                "all_players_confirm",
                name="verification_policy",
            ),
            server_default="none",
            nullable=False,
        ),
        sa.Column(
            "retirement_window",
            sa.Interval(),
            server_default=sa.text("'7 days'"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "retirement_window IS NULL OR retirement_window > interval '0'",
            name="ck_match_settings_retirement_window_positive",
        ),
        sa.CheckConstraint(
            "best_of >= 1 AND best_of % 2 = 1", name="ck_match_settings_best_of"
        ),
        sa.CheckConstraint("team_size IN (1, 2)", name="ck_match_settings_team_size"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notification_channels",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("key", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "display_order", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "is_available", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notification_channels_key"),
        "notification_channels",
        ["key"],
        unique=True,
    )
    op.create_table(
        "notification_types",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("key", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("short_label", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "display_order", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notification_types_key"), "notification_types", ["key"], unique=True
    )
    op.create_table(
        "permissions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1024), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_permissions_name"), "permissions", ["name"], unique=True)
    op.create_table(
        "players",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("merged_into_player_id", sa.UUID(), nullable=True),
        sa.Column("merged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(merged_at IS NULL) = (merged_into_player_id IS NULL)",
            name="ck_players_tombstone_pair",
        ),
        sa.CheckConstraint(
            "merged_into_player_id <> id", name="ck_players_not_self_merged"
        ),
        sa.ForeignKeyConstraint(
            ["merged_into_player_id"], ["players.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_players_merged_into_player_id"),
        "players",
        ["merged_into_player_id"],
        unique=False,
    )
    op.create_index(op.f("ix_players_username"), "players", ["username"], unique=True)
    op.create_table(
        "rating_strategies",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "state_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "initial_state", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("initial_rating_value", sa.Float(), nullable=True),
        sa.Column(
            "is_automatic",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rating_strategies_key"), "rating_strategies", ["key"], unique=True
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1024), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_roles_name"), "roles", ["name"], unique=True)
    op.create_table(
        "account_players",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column(
            "is_primary", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("account_id", "player_id"),
    )
    op.create_index(
        "uq_account_players_primary",
        "account_players",
        ["account_id"],
        unique=True,
        postgresql_where=sa.text("is_primary"),
    )
    op.create_table(
        "device_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("token", sa.String(length=512), nullable=False),
        sa.Column("platform", sa.String(length=16), nullable=False),
        sa.Column("environment", sa.String(length=16), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token", name="uq_device_tokens_token"),
    )
    op.create_index(
        op.f("ix_device_tokens_user_id"), "device_tokens", ["user_id"], unique=False
    )
    op.create_table(
        "leagues",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "visibility",
            sa.Enum("public", "private", name="league_visibility"),
            server_default="public",
            nullable=False,
        ),
        sa.Column(
            "is_default", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("rating_strategy_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["rating_strategy_id"], ["rating_strategies.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_leagues_name"), "leagues", ["name"], unique=True)
    op.create_index(
        op.f("ix_leagues_rating_strategy_id"),
        "leagues",
        ["rating_strategy_id"],
        unique=False,
    )
    op.create_index(
        "uq_leagues_one_default",
        "leagues",
        ["is_default"],
        unique=True,
        postgresql_where=sa.text("is_default"),
    )
    op.create_table(
        "login_identities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("issuer", sa.String(length=512), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("subject", sa.String(length=512), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "account_id",
            "issuer",
            "provider",
            name="uq_login_identities_account_provider",
        ),
        sa.UniqueConstraint(
            "issuer", "provider", "subject", name="uq_login_identities_subject"
        ),
    )
    op.create_index(
        op.f("ix_login_identities_account_id"),
        "login_identities",
        ["account_id"],
        unique=False,
    )
    op.create_table(
        "notification_channel_settings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["channel"], ["notification_channels.key"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "channel", name="uq_notification_channel_settings_user_channel"
        ),
    )
    op.create_table(
        "notification_preferences",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category"], ["notification_types.key"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["channel"], ["notification_channels.key"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "category",
            "channel",
            name="uq_notification_preferences_user_category_channel",
        ),
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("permission_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"], ["permissions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
    )
    op.create_table(
        "tournament_event_draw_settings",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("draw_type_id", sa.UUID(), nullable=False),
        sa.Column(
            "settings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(settings) = 'object'",
            name="ck_tournament_event_draw_settings_settings_object",
        ),
        sa.ForeignKeyConstraint(
            ["draw_type_id"], ["draw_types.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
    )
    op.create_table(
        "user_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("token", sa.LargeBinary(), nullable=False),
        sa.Column("context", sa.String(length=255), nullable=False),
        sa.Column("sent_to", sa.String(length=255), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("replaced_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_user_tokens_replaced_pending_email",
        "user_tokens",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text(
            "replaced_at IS NOT NULL AND (context LIKE 'change:%' OR "
            "context LIKE 'merge:%')"
        ),
    )
    op.create_index(
        op.f("ix_user_tokens_token"), "user_tokens", ["token"], unique=False
    )
    op.create_index(
        op.f("ix_user_tokens_user_id"), "user_tokens", ["user_id"], unique=False
    )
    op.create_table(
        "league_memberships",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("league_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["league_id"], ["leagues.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["players.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "league_id", "user_id", name="uq_league_memberships_league_id_user_id"
        ),
    )
    op.create_index(
        "ix_league_memberships_user_id", "league_memberships", ["user_id"], unique=False
    )
    op.create_table(
        "matches",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("match_settings_id", sa.UUID(), nullable=False),
        sa.Column("league_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "in_progress", "completed", "voided", name="match_status"
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["accounts.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["league_id"], ["leagues.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["match_settings_id"], ["match_settings.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_matches_created_by_user_id_created_at",
        "matches",
        ["created_by_user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index("ix_matches_league_id", "matches", ["league_id"], unique=False)
    op.create_index(
        "ix_matches_status_completed_at",
        "matches",
        ["status", sa.literal_column("completed_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_matches_status_created_at",
        "matches",
        ["status", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_matches_status_updated_at",
        "matches",
        ["status", sa.literal_column("updated_at DESC")],
        unique=False,
    )
    op.create_table(
        "tournaments",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "details_version", sa.Integer(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("draft", "published", "live", "archived", name="tournament_status"),
            server_default="draft",
            nullable=False,
        ),
        sa.Column(
            "address",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("league_id", sa.UUID(), nullable=False),
        sa.Column("owner_account_id", sa.UUID(), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["accounts.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["league_id"], ["leagues.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["owner_account_id"], ["accounts.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_tournaments_created_by_user_id_created_at",
        "tournaments",
        ["created_by_user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_tournaments_owner_account_id"),
        "tournaments",
        ["owner_account_id"],
        unique=False,
    )
    op.create_table(
        "user_league_ratings",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("league_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("rating_strategy_id", sa.UUID(), nullable=False),
        sa.Column("rating_value", sa.Float(), nullable=True),
        sa.Column(
            "rating_state", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["league_id"], ["leagues.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["rating_strategy_id"], ["rating_strategies.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["players.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "league_id", "user_id", name="uq_user_league_ratings_league_id_user_id"
        ),
    )
    op.create_index(
        "ix_user_league_ratings_user_id",
        "user_league_ratings",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "match_games",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("match_id", sa.UUID(), nullable=False),
        sa.Column("game_number", sa.SmallInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("game_number >= 1", name="ck_match_games_game_number"),
        sa.ForeignKeyConstraint(["match_id"], ["matches.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "match_id", "game_number", name="uq_match_games_match_id_game_number"
        ),
    )
    op.create_index(
        "ix_match_games_match_id", "match_games", ["match_id"], unique=False
    )
    op.create_table(
        "match_results",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("match_id", sa.UUID(), nullable=False),
        sa.Column("submitted_by_user_id", sa.UUID(), nullable=False),
        sa.Column("submitted_for_player_id", sa.UUID(), nullable=True),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("supersedes_result_id", sa.UUID(), nullable=True),
        sa.Column("accepted_by_user_id", sa.UUID(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reminder_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("games", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "(accepted_by_user_id IS NULL) = (accepted_at IS NULL)",
            name="ck_match_results_accepted_pair",
        ),
        sa.ForeignKeyConstraint(
            ["accepted_by_user_id"], ["accounts.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["match_id"], ["matches.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["submitted_by_user_id"], ["accounts.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["submitted_for_player_id"], ["players.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_result_id"], ["match_results.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "supersedes_result_id", name="uq_match_results_supersedes_result_id"
        ),
    )
    op.create_index(
        "ix_match_results_match_id", "match_results", ["match_id"], unique=False
    )
    op.create_table(
        "match_sides",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("match_id", sa.UUID(), nullable=False),
        sa.Column("side_number", sa.SmallInteger(), nullable=False),
        sa.Column(
            "score", sa.SmallInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("won", sa.Boolean(), nullable=True),
        sa.CheckConstraint("score >= 0", name="ck_match_sides_score"),
        sa.CheckConstraint("side_number IN (1, 2)", name="ck_match_sides_side_number"),
        sa.ForeignKeyConstraint(["match_id"], ["matches.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "match_id", name="uq_match_sides_id_match_id"),
        sa.UniqueConstraint(
            "match_id", "side_number", name="uq_match_sides_match_id_side_number"
        ),
    )
    op.create_index(
        "ix_match_sides_match_id", "match_sides", ["match_id"], unique=False
    )
    op.create_table(
        "rating_history",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("league_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("match_id", sa.UUID(), nullable=True),
        sa.Column("rating_strategy_id", sa.UUID(), nullable=False),
        sa.Column("rating_value", sa.Float(), nullable=False),
        sa.Column(
            "rating_state", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("previous_rating_value", sa.Float(), nullable=True),
        sa.Column(
            "source",
            sa.Enum(
                "match", "manual", "import", "initial", name="rating_history_source"
            ),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["accounts.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["league_id"], ["leagues.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["match_id"], ["matches.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["rating_strategy_id"], ["rating_strategies.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["players.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_rating_history_league_id_user_id_created_at",
        "rating_history",
        ["league_id", "user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_rating_history_match_id", "rating_history", ["match_id"], unique=False
    )
    op.create_index(
        "uq_rating_history_match_id_user_id",
        "rating_history",
        ["match_id", "user_id"],
        unique=True,
        postgresql_where=sa.text("match_id IS NOT NULL"),
    )
    op.create_table(
        "schedule_solves",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("tournament_id", sa.UUID(), nullable=False),
        sa.Column(
            "trigger",
            sa.Enum(
                "go_live",
                "match_completed",
                "settings_changed",
                "manual",
                "pin_tick",
                "rerun",
                name="schedule_solve_trigger",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "succeeded",
                "infeasible",
                "failed",
                name="schedule_solve_status",
            ),
            server_default="queued",
            nullable=False,
        ),
        sa.Column(
            "verdict",
            sa.Enum("optimal", "feasible", "infeasible", name="solver_verdict"),
            nullable=True,
        ),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("wall_time_ms", sa.Integer(), nullable=True),
        sa.Column("fixtures_placed", sa.Integer(), nullable=True),
        sa.Column("fixtures_pinned", sa.Integer(), nullable=True),
        sa.Column(
            "overrunning", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("input_fingerprint", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "infeasibility_reasons",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "placement_conflicts",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "rerun_requested",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tournament_id"], ["tournaments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_schedule_solves_tournament_id_requested_at",
        "schedule_solves",
        ["tournament_id", sa.literal_column("requested_at DESC")],
        unique=False,
    )
    op.create_table(
        "tournament_events",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("tournament_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "format",
            sa.Enum("singles", "doubles", "teams", name="event_format"),
            nullable=False,
        ),
        sa.Column("draw_settings_id", sa.UUID(), nullable=False),
        sa.Column("max_players", sa.Integer(), nullable=True),
        sa.Column("entry_fee", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("slot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "match_settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "predicates",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "lock_version", sa.Integer(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "entry_fee >= 0", name="ck_tournament_events_entry_fee_non_negative"
        ),
        sa.CheckConstraint(
            "max_players > 0", name="ck_tournament_events_max_players_positive"
        ),
        sa.ForeignKeyConstraint(
            ["draw_settings_id"],
            ["tournament_event_draw_settings.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tournament_id"], ["tournaments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tournament_id", "id", name="uq_tournament_events_tournament_id_id"
        ),
    )
    op.create_index(
        op.f("ix_tournament_events_draw_settings_id"),
        "tournament_events",
        ["draw_settings_id"],
        unique=False,
    )
    op.create_index(
        "ix_tournament_events_tournament_id_created_at",
        "tournament_events",
        ["tournament_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "tournament_tables",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("tournament_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("court", sa.String(length=255), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tournament_id"], ["tournaments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tournament_id", "id", name="uq_tournament_tables_tournament_id_id"
        ),
        sa.UniqueConstraint(
            "tournament_id",
            "position",
            deferrable=True,
            initially="DEFERRED",
            name="uq_tournament_tables_tournament_position",
        ),
    )
    op.create_index(
        "ix_tournament_tables_tournament_id_position",
        "tournament_tables",
        ["tournament_id", "position"],
        unique=False,
    )
    op.create_table(
        "match_game_scores",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("match_game_id", sa.UUID(), nullable=False),
        sa.Column("side_1_points", sa.SmallInteger(), nullable=False),
        sa.Column("side_2_points", sa.SmallInteger(), nullable=False),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "side_1_points >= 0", name="ck_match_game_scores_side_1_points"
        ),
        sa.CheckConstraint(
            "side_2_points >= 0", name="ck_match_game_scores_side_2_points"
        ),
        sa.ForeignKeyConstraint(
            ["match_game_id"], ["match_games.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("match_game_id", name="uq_match_game_scores_match_game_id"),
    )
    op.create_table(
        "match_side_players",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("match_side_id", sa.UUID(), nullable=False),
        sa.Column("match_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["match_id"], ["matches.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["match_side_id", "match_id"],
            ["match_sides.id", "match_sides.match_id"],
            name="fk_match_side_players_side_match",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["players.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "match_id", "user_id", name="uq_match_side_players_match_id_user_id"
        ),
        sa.UniqueConstraint(
            "match_side_id",
            "user_id",
            name="uq_match_side_players_match_side_id_user_id",
        ),
    )
    op.create_index(
        "ix_match_side_players_match_side_id",
        "match_side_players",
        ["match_side_id"],
        unique=False,
    )
    op.create_index(
        "ix_match_side_players_user_id", "match_side_players", ["user_id"], unique=False
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.String(length=500), nullable=False),
        sa.Column("link", sa.String(length=512), nullable=True),
        sa.Column("action_label", sa.String(length=40), nullable=True),
        sa.Column("delta", sa.String(length=16), nullable=True),
        sa.Column("result_id", sa.UUID(), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category"], ["notification_types.key"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["result_id"], ["match_results.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_notifications_result_id", "notifications", ["result_id"], unique=False
    )
    op.create_index(
        "ix_notifications_user_id_created_at",
        "notifications",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "tournament_entries",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("added_by_user_id", sa.UUID(), nullable=True),
        sa.Column("seed", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("entered", "withdrawn", name="tournament_entry_status"),
            server_default="entered",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["added_by_user_id"], ["accounts.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["tournament_events.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["players.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_tournament_entries_added_by_user_id",
        "tournament_entries",
        ["added_by_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_tournament_entries_event_id",
        "tournament_entries",
        ["event_id"],
        unique=False,
    )
    op.create_index(
        "ix_tournament_entries_user_id", "tournament_entries", ["user_id"], unique=False
    )
    op.create_index(
        "uq_tournament_entries_event_id_user_id_active",
        "tournament_entries",
        ["event_id", "user_id"],
        unique=True,
        postgresql_where=sa.text("status = 'entered'"),
    )
    op.create_table(
        "tournament_event_reservations",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("slot_date", sa.Date(), nullable=False),
        sa.Column("slot_start", sa.Time(), nullable=False),
        sa.Column("slot_end", sa.Time(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["tournament_events.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_tournament_event_reservations"),
        sa.UniqueConstraint(
            "event_id", "id", name="uq_tournament_event_reservations_event_id_id"
        ),
        sa.UniqueConstraint(
            "event_id",
            "position",
            deferrable=True,
            initially="DEFERRED",
            name="uq_tournament_event_reservations_event_id_position",
        ),
    )
    op.create_table(
        "tournament_event_stages",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("draw_type_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["draw_type_id"], ["draw_types.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["tournament_events.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "event_id", "id", name="uq_tournament_event_stages_event_id_id"
        ),
        sa.UniqueConstraint(
            "event_id", "position", name="uq_tournament_event_stages_event_id_position"
        ),
    )
    op.create_table(
        "tournament_event_reservation_tables",
        sa.Column("tournament_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("reservation_id", sa.UUID(), nullable=False),
        sa.Column("table_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_id", "reservation_id"],
            [
                "tournament_event_reservations.event_id",
                "tournament_event_reservations.id",
            ],
            name="fk_tournament_event_reservation_tables_event_id_reservation_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tournament_id", "event_id"],
            ["tournament_events.tournament_id", "tournament_events.id"],
            name="fk_tournament_event_reservation_tables_tournament_id_event_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tournament_id", "table_id"],
            ["tournament_tables.tournament_id", "tournament_tables.id"],
            name="fk_tournament_event_reservation_tables_tournament_id_table_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "event_id",
            "reservation_id",
            "table_id",
            name="pk_tournament_event_reservation_tables",
        ),
        sa.UniqueConstraint(
            "event_id",
            "reservation_id",
            "position",
            deferrable=True,
            initially="DEFERRED",
            name="uq_tournament_event_reservation_tables_reservation_position",
        ),
    )
    op.create_index(
        "ix_tournament_event_reservation_tables_tournament_id_table_id",
        "tournament_event_reservation_tables",
        ["tournament_id", "table_id"],
        unique=False,
    )
    op.create_table(
        "tournament_event_stage_groups",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("stage_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["stage_id"], ["tournament_event_stages.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_tournament_event_stage_groups"),
        sa.UniqueConstraint(
            "stage_id", "id", name="uq_tournament_event_stage_groups_stage_id_id"
        ),
        sa.UniqueConstraint(
            "stage_id",
            "position",
            deferrable=True,
            initially="DEFERRED",
            name="uq_tournament_event_stage_groups_stage_id_position",
        ),
    )
    op.create_table(
        "tournament_event_group_reservations",
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("stage_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("reservation_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_id", "reservation_id"],
            [
                "tournament_event_reservations.event_id",
                "tournament_event_reservations.id",
            ],
            name="fk_tournament_event_group_reservations_event_id_reservation_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["event_id", "stage_id"],
            ["tournament_event_stages.event_id", "tournament_event_stages.id"],
            name="fk_tournament_event_group_reservations_event_id_stage_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["stage_id", "group_id"],
            [
                "tournament_event_stage_groups.stage_id",
                "tournament_event_stage_groups.id",
            ],
            name="fk_tournament_event_group_reservations_stage_id_group_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "group_id", name="pk_tournament_event_group_reservations"
        ),
    )
    op.create_index(
        "ix_tournament_event_group_reservations_event_id_reservation_id",
        "tournament_event_group_reservations",
        ["event_id", "reservation_id"],
        unique=False,
    )
    op.create_index(
        "ix_tournament_event_group_reservations_event_id_stage_id",
        "tournament_event_group_reservations",
        ["event_id", "stage_id"],
        unique=False,
    )
    op.create_table(
        "tournament_fixtures",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("stage_id", sa.UUID(), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("round", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("entry_a_id", sa.UUID(), nullable=True),
        sa.Column("entry_b_id", sa.UUID(), nullable=True),
        sa.Column("winner_entry_id", sa.UUID(), nullable=True),
        sa.Column("match_id", sa.UUID(), nullable=True),
        sa.Column("table_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("scheduled_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pinned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "call_notified_count",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["entry_a_id"], ["tournament_entries.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["entry_b_id"], ["tournament_entries.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["match_id"], ["matches.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["stage_id", "group_id"],
            [
                "tournament_event_stage_groups.stage_id",
                "tournament_event_stage_groups.id",
            ],
            name="fk_tournament_fixtures_stage_id_group_id",
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.ForeignKeyConstraint(
            ["stage_id"], ["tournament_event_stages.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["table_id"], ["tournament_tables.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["winner_entry_id"], ["tournament_entries.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "stage_id",
            "group_id",
            "round",
            "position",
            name="uq_tournament_fixtures_stage_id_group_id_round_position",
        ),
    )
    op.create_index(
        "ix_tournament_fixtures_match_id",
        "tournament_fixtures",
        ["match_id"],
        unique=False,
    )
    op.create_index(
        "ix_tournament_fixtures_stage_id",
        "tournament_fixtures",
        ["stage_id"],
        unique=False,
    )
    op.create_index(
        "ix_tournament_fixtures_table_id",
        "tournament_fixtures",
        ["table_id"],
        unique=False,
    )
    # ### end Alembic commands ###
    op.bulk_insert(
        sa.table(
            "rating_strategies",
            sa.column("id", sa.UUID()),
            sa.column("key", sa.String()),
            sa.column("name", sa.String()),
            sa.column("description", sa.Text()),
            sa.column("state_schema", postgresql.JSONB()),
            sa.column("initial_state", postgresql.JSONB()),
            sa.column("initial_rating_value", sa.Float()),
            sa.column("is_automatic", sa.Boolean()),
        ),
        [
            {
                "description": "Glicko-2 — tracks both skill (rating) and "
                "uncertainty (RD + "
                "volatility). Updated automatically on each rated match.",
                "id": UUID("11111111-1111-1111-1111-111111110001"),
                "initial_rating_value": 1500.0,
                "initial_state": {"rating": 1500.0, "rd": 350.0, "volatility": 0.06},
                "is_automatic": True,
                "key": "glicko2",
                "name": "Glicko-2",
                "state_schema": {
                    "additionalProperties": False,
                    "properties": {
                        "rating": {"type": "number"},
                        "rd": {"type": "number"},
                        "volatility": {"type": "number"},
                    },
                    "required": ["rating", "rd", "volatility"],
                    "type": "object",
                },
            },
            {
                "description": "Ratings supplied externally (e.g. USATT) or by "
                "admin entry. Match "
                "completion does not change ratings in a manual league.",
                "id": UUID("11111111-1111-1111-1111-111111110002"),
                "initial_rating_value": None,
                "initial_state": None,
                "is_automatic": False,
                "key": "manual",
                "name": "Manual / external",
                "state_schema": {
                    "additionalProperties": False,
                    "properties": {"rating": {"type": "number"}},
                    "required": ["rating"],
                    "type": "object",
                },
            },
        ],
    )

    op.bulk_insert(
        sa.table(
            "notification_types",
            sa.column("id", sa.UUID()),
            sa.column("key", sa.String()),
            sa.column("name", sa.String()),
            sa.column("short_label", sa.String()),
            sa.column("display_order", sa.Integer()),
            sa.column("is_active", sa.Boolean()),
        ),
        [
            {
                "display_order": 1,
                "id": UUID("33333333-3333-3333-3333-333333330001"),
                "is_active": True,
                "key": "match_reminder",
                "name": "Match reminders",
                "short_label": "Match",
            },
            {
                "display_order": 2,
                "id": UUID("33333333-3333-3333-3333-333333330002"),
                "is_active": True,
                "key": "rating_change",
                "name": "Rating changes",
                "short_label": "Rating",
            },
            {
                "display_order": 3,
                "id": UUID("33333333-3333-3333-3333-333333330003"),
                "is_active": True,
                "key": "tournament",
                "name": "Tournament news",
                "short_label": "Tourney",
            },
            {
                "display_order": 4,
                "id": UUID("33333333-3333-3333-3333-333333330004"),
                "is_active": True,
                "key": "opponent",
                "name": "Challenges & friends",
                "short_label": "Social",
            },
            {
                "display_order": 5,
                "id": UUID("33333333-3333-3333-3333-333333330005"),
                "is_active": True,
                "key": "result_confirm",
                "name": "Score acceptances",
                "short_label": "Scores",
            },
            {
                "display_order": 6,
                "id": UUID("33333333-3333-3333-3333-333333330006"),
                "is_active": True,
                "key": "match_calls",
                "name": "Match calls",
                "short_label": "Calls",
            },
        ],
    )

    op.bulk_insert(
        sa.table(
            "notification_channels",
            sa.column("id", sa.UUID()),
            sa.column("key", sa.String()),
            sa.column("name", sa.String()),
            sa.column("display_order", sa.Integer()),
            sa.column("is_active", sa.Boolean()),
            sa.column("is_available", sa.Boolean()),
        ),
        [
            {
                "display_order": 1,
                "id": UUID("44444444-4444-4444-4444-444444440001"),
                "is_active": True,
                "is_available": True,
                "key": "in_app",
                "name": "In-app",
            },
            {
                "display_order": 2,
                "id": UUID("44444444-4444-4444-4444-444444440002"),
                "is_active": True,
                "is_available": True,
                "key": "push",
                "name": "Push",
            },
            {
                "display_order": 3,
                "id": UUID("44444444-4444-4444-4444-444444440003"),
                "is_active": True,
                "is_available": True,
                "key": "email",
                "name": "Email",
            },
            {
                "display_order": 4,
                "id": UUID("44444444-4444-4444-4444-444444440004"),
                "is_active": True,
                "is_available": False,
                "key": "sms",
                "name": "SMS",
            },
        ],
    )

    op.bulk_insert(
        sa.table(
            "draw_types",
            sa.column("id", sa.UUID()),
            sa.column("key", sa.String()),
            sa.column("name", sa.String()),
            sa.column("description", sa.Text()),
            sa.column("display_order", sa.Integer()),
        ),
        [
            {
                "description": "Everyone in a group plays everyone else in that "
                "group. Every entrant "
                "is guaranteed the same number of matches and the final standings "
                "rank the whole field, so it is the fairest read on form — but the "
                "match count climbs quickly with group size, and the event needs at "
                "least one group.",
                "display_order": 1,
                "id": UUID("22222222-2222-2222-2222-222222220001"),
                "key": "round-robin",
                "name": "Round robin",
            },
            {
                "description": "A knockout bracket: lose once and you are out. It "
                "crowns a champion "
                "in the fewest matches and the least table time, which suits a large "
                "field or a tight schedule — but half the entrants are finished after "
                "one match, and a field that is not a power of two gives the top "
                "seeds byes.",
                "display_order": 2,
                "id": UUID("22222222-2222-2222-2222-222222220002"),
                "key": "single-elim",
                "name": "Single elimination",
            },
            {
                "description": "Groups play all-play-all, then the top finishers "
                "from each group "
                "meet in a knockout bracket.",
                "display_order": 3,
                "id": UUID("22222222-2222-2222-2222-222222220003"),
                "key": "rr-then-ko",
                "name": "Round-robin then knockout",
            },
            {
                "description": "A fixed number of rounds, each pairing entrants "
                "who are on similar "
                "scores. Nobody is eliminated and everybody plays every round, so a "
                "large field is ranked in far fewer matches than a round robin — but "
                "a round's pairings are only known once the round before it has "
                "finished, and a long event may repeat a pairing.",
                "display_order": 4,
                "id": UUID("22222222-2222-2222-2222-222222220004"),
                "key": "swiss",
                "name": "Swiss",
            },
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tournament_fixtures_table_id", table_name="tournament_fixtures")
    op.drop_index("ix_tournament_fixtures_stage_id", table_name="tournament_fixtures")
    op.drop_index("ix_tournament_fixtures_match_id", table_name="tournament_fixtures")
    op.drop_table("tournament_fixtures")
    op.drop_index(
        "ix_tournament_event_group_reservations_event_id_stage_id",
        table_name="tournament_event_group_reservations",
    )
    op.drop_index(
        "ix_tournament_event_group_reservations_event_id_reservation_id",
        table_name="tournament_event_group_reservations",
    )
    op.drop_table("tournament_event_group_reservations")
    op.drop_table("tournament_event_stage_groups")
    op.drop_index(
        "ix_tournament_event_reservation_tables_tournament_id_table_id",
        table_name="tournament_event_reservation_tables",
    )
    op.drop_table("tournament_event_reservation_tables")
    op.drop_table("tournament_event_stages")
    op.drop_table("tournament_event_reservations")
    op.drop_index(
        "uq_tournament_entries_event_id_user_id_active",
        table_name="tournament_entries",
        postgresql_where=sa.text("status = 'entered'"),
    )
    op.drop_index("ix_tournament_entries_user_id", table_name="tournament_entries")
    op.drop_index("ix_tournament_entries_event_id", table_name="tournament_entries")
    op.drop_index(
        "ix_tournament_entries_added_by_user_id", table_name="tournament_entries"
    )
    op.drop_table("tournament_entries")
    op.drop_index("ix_notifications_user_id_created_at", table_name="notifications")
    op.drop_index("ix_notifications_result_id", table_name="notifications")
    op.drop_table("notifications")
    op.drop_index("ix_match_side_players_user_id", table_name="match_side_players")
    op.drop_index(
        "ix_match_side_players_match_side_id", table_name="match_side_players"
    )
    op.drop_table("match_side_players")
    op.drop_table("match_game_scores")
    op.drop_index(
        "ix_tournament_tables_tournament_id_position", table_name="tournament_tables"
    )
    op.drop_table("tournament_tables")
    op.drop_index(
        "ix_tournament_events_tournament_id_created_at", table_name="tournament_events"
    )
    op.drop_index(
        op.f("ix_tournament_events_draw_settings_id"), table_name="tournament_events"
    )
    op.drop_table("tournament_events")
    op.drop_index(
        "ix_schedule_solves_tournament_id_requested_at", table_name="schedule_solves"
    )
    op.drop_table("schedule_solves")
    op.drop_index(
        "uq_rating_history_match_id_user_id",
        table_name="rating_history",
        postgresql_where=sa.text("match_id IS NOT NULL"),
    )
    op.drop_index("ix_rating_history_match_id", table_name="rating_history")
    op.drop_index(
        "ix_rating_history_league_id_user_id_created_at", table_name="rating_history"
    )
    op.drop_table("rating_history")
    op.drop_index("ix_match_sides_match_id", table_name="match_sides")
    op.drop_table("match_sides")
    op.drop_index("ix_match_results_match_id", table_name="match_results")
    op.drop_table("match_results")
    op.drop_index("ix_match_games_match_id", table_name="match_games")
    op.drop_table("match_games")
    op.drop_index("ix_user_league_ratings_user_id", table_name="user_league_ratings")
    op.drop_table("user_league_ratings")
    op.drop_index(op.f("ix_tournaments_owner_account_id"), table_name="tournaments")
    op.drop_index(
        "ix_tournaments_created_by_user_id_created_at", table_name="tournaments"
    )
    op.drop_table("tournaments")
    op.drop_index("ix_matches_status_updated_at", table_name="matches")
    op.drop_index("ix_matches_status_created_at", table_name="matches")
    op.drop_index("ix_matches_status_completed_at", table_name="matches")
    op.drop_index("ix_matches_league_id", table_name="matches")
    op.drop_index("ix_matches_created_by_user_id_created_at", table_name="matches")
    op.drop_table("matches")
    op.drop_index("ix_league_memberships_user_id", table_name="league_memberships")
    op.drop_table("league_memberships")
    op.drop_index(op.f("ix_user_tokens_user_id"), table_name="user_tokens")
    op.drop_index(op.f("ix_user_tokens_token"), table_name="user_tokens")
    op.drop_index(
        "ix_user_tokens_replaced_pending_email",
        table_name="user_tokens",
        postgresql_where=sa.text(
            "replaced_at IS NOT NULL AND (context LIKE 'change:%' OR "
            "context LIKE 'merge:%')"
        ),
    )
    op.drop_table("user_tokens")
    op.drop_table("user_roles")
    op.drop_table("tournament_event_draw_settings")
    op.drop_table("role_permissions")
    op.drop_table("notification_preferences")
    op.drop_table("notification_channel_settings")
    op.drop_index(op.f("ix_login_identities_account_id"), table_name="login_identities")
    op.drop_table("login_identities")
    op.drop_index(
        "uq_leagues_one_default",
        table_name="leagues",
        postgresql_where=sa.text("is_default"),
    )
    op.drop_index(op.f("ix_leagues_rating_strategy_id"), table_name="leagues")
    op.drop_index(op.f("ix_leagues_name"), table_name="leagues")
    op.drop_table("leagues")
    op.drop_index(op.f("ix_device_tokens_user_id"), table_name="device_tokens")
    op.drop_table("device_tokens")
    op.drop_index(
        "uq_account_players_primary",
        table_name="account_players",
        postgresql_where=sa.text("is_primary"),
    )
    op.drop_table("account_players")
    op.drop_index(op.f("ix_roles_name"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_rating_strategies_key"), table_name="rating_strategies")
    op.drop_table("rating_strategies")
    op.drop_index(op.f("ix_players_username"), table_name="players")
    op.drop_index(op.f("ix_players_merged_into_player_id"), table_name="players")
    op.drop_table("players")
    op.drop_index(op.f("ix_permissions_name"), table_name="permissions")
    op.drop_table("permissions")
    op.drop_index(op.f("ix_notification_types_key"), table_name="notification_types")
    op.drop_table("notification_types")
    op.drop_index(
        op.f("ix_notification_channels_key"), table_name="notification_channels"
    )
    op.drop_table("notification_channels")
    op.drop_table("match_settings")
    op.drop_table("draw_types")
    op.drop_index(op.f("ix_accounts_merged_into_user_id"), table_name="accounts")
    op.drop_index(op.f("ix_accounts_email"), table_name="accounts")
    op.drop_table("accounts")
    # ### end Alembic commands ###
    postgresql.ENUM(name="event_format").drop(op.get_bind(), checkfirst=True)

    postgresql.ENUM(name="league_visibility").drop(op.get_bind(), checkfirst=True)

    postgresql.ENUM(name="match_status").drop(op.get_bind(), checkfirst=True)

    postgresql.ENUM(name="rating_history_source").drop(op.get_bind(), checkfirst=True)

    postgresql.ENUM(name="schedule_solve_status").drop(op.get_bind(), checkfirst=True)

    postgresql.ENUM(name="schedule_solve_trigger").drop(op.get_bind(), checkfirst=True)

    postgresql.ENUM(name="solver_verdict").drop(op.get_bind(), checkfirst=True)

    postgresql.ENUM(name="tournament_entry_status").drop(op.get_bind(), checkfirst=True)

    postgresql.ENUM(name="tournament_status").drop(op.get_bind(), checkfirst=True)

    postgresql.ENUM(name="verification_policy").drop(op.get_bind(), checkfirst=True)
