// @ts-check
/**
 * Mutation testing config — StrykerJS over the existing Vitest suite.
 *
 * Stryker rewrites the production source with small faults ("mutants") and
 * re-runs only the tests that cover each one. A mutant that no test catches is
 * a gap in the suite's assertions — signal that line/branch coverage can't give.
 *
 * Run with `npm run test:mutation`. Reports land in `reports/mutation/`.
 *
 * `npm run test:mutation:changed` (scripts/mutation-changed.ts) scopes a run
 * to the files changed vs a base ref; it imports this config and reuses the
 * `!`-exclusions from `mutate`, so the exclusion list lives only here.
 *
 * @type {import('@stryker-mutator/api/core').PartialStrykerOptions}
 */
export default {
  packageManager: "npm",
  testRunner: "vitest",

  // Discard mutants that don't type-check before wasting a test run on them.
  checkers: ["typescript"],
  tsconfigFile: "tsconfig.app.json",

  // The vitest runner reuses vite.config.ts (jsdom env, MSW setupFiles, the
  // `@` alias), so mutated code runs through the same harness as the real suite.
  // perTest coverage lets Stryker run only the tests that touch each mutant.
  coverageAnalysis: "perTest",

  reporters: ["html", "clear-text", "progress"],
  htmlReporter: { fileName: "reports/mutation/index.html" },

  // What to mutate: the production source where logic actually lives. Everything
  // excluded below is either generated, vendored, or test infrastructure —
  // mutating it burns time and produces a meaningless score.
  mutate: [
    "src/**/*.{ts,tsx}",
    "!src/**/*.test.{ts,tsx}",
    "!src/**/*.page.tsx", // page objects (test-only DOM access)
    "!src/**/*.factory.{ts,tsx}", // test data builders
    "!src/**/*-skeleton.tsx", // pure <Suspense> fallbacks, no logic
    "!src/components/ui/**", // shadcn primitives (vendored)
    "!src/mocks/**", // MSW handlers + fixtures
    "!src/test/**", // vitest setup
    "!src/routeTree.gen.ts", // generated by the router plugin
    "!src/api/schema.d.ts", // generated from openapi.json
    "!src/**/*.gen.ts",
    "!src/main.tsx", // app bootstrap
    "!src/vite-env.d.ts",
  ],

  // Quality bars for the score, not a build gate (break: null). Flip `break` to
  // a number once there's a stable baseline to ratchet against.
  thresholds: { high: 80, low: 60, break: null },
};
